### ISSUE TITLE
Ενδεχόμενο παράτασης

### ISSUE THREAD

**Issue by Evangelia0** [slp-ntua/patrec-labs#100]
Θα μπορούσε μήπως να δοθεί μία παράταση στην 1η εργαστηριακή άσκηση για 2-3 μέρες δηλαδή έως και την Παρασκευή; Έτσι θα έχουμε και λίγο περισσότερο χρόνο να τρέξουμε περισσότερα τεστς και στο 19 και να βγει καλύτερη η τελική αναφορά.

**Comment by iliaskoum** [comment]
+1

**Comment by johnliak** [comment]
+1

**Comment by Despoinam** [comment]
+1

**Comment by Desoforos** [comment]
+1

**Comment by VironZmb** [comment]
Συμφωνώ ότι θα βοηθούσε πολύ μία μικρή παράταση. Το επόμενο μάθημα είναι την Πέμπτη οπότε δεν θα υπάρξει καθυστερήση αν δοθεί παράταση τουλάχιστον μέχρι τότε.

**Comment by StefanosVks7** [comment]
+1

**Comment by yasonkal** [comment]
+1

**Comment by nonistrati** [comment]
+1

**Comment by geokyr** [comment]
+1

**Comment by dimitrismit** [comment]
+1

**Comment by Tsaousis** [comment]
+1

**Comment by georgepar** [comment]
Ισχύει αυτό που έχουμε πει στο εργαστήριο. 
Μπορείτε να παραδώσετε μέχρι την επόμενη Δευτέρα με -10% πέναλτι στο βαθμό του εργαστηρίου.
