### ISSUE TITLE
[Βήμα 19γ]

### ISSUE THREAD

**Issue by dion11ar** [slp-ntua/patrec-labs#101]
Καλησπέρα, μπορείτε να μας εξηγήσετε σε τι χρειάζεται το valdiation set για την εκπαίδευση του νευρωνικού;
Ευχαριστώ πολύ για τον χρόνο σας

**Comment by georgepar** [comment]
Το validation set χρειάζεται για τους ίδιους λόγους που χρειάζεται να κάνουμε cross-validation (ρύθμιση υπερπαραμέτρων κτλ)
(βλ https://github.com/slp-ntua/python-lab/blob/master/Lab%200.3%20Scikit-learn.ipynb).

Απλά επειδή τα νευρωνικά χρησιμοποιούνται σε πιο μεγάλα dataset και χρειάζονται πιο πολύ ώρα για την εκπαίδευση, αντί να κάνουμε cross-validation που απαιτεί την εκπαίδευση 5-10 μοντέλων χρησιμοποιούμε συνήθως ένα validation set για αυτό το λόγο.

Μπορείς να διαβάσεις και αυτό το [blog](https://tarangshah.com/blog/2017-12-03/train-validation-and-test-sets/) για παραπάνω.
