### ISSUE TITLE
Παράδοση και lib.py?

### ISSUE THREAD

**Issue by el2kaps** [slp-ntua/patrec-labs#102]
Καλησπέρα, είναι απαραίτητο να στείλουμε και το lib.py? Έχουμε υλοποιήσει κλάσεις και συναρτήσεις στη μορφή που είναι στο lib.py αλλά είναι σε ένα αρχείο μαζί με τον κύριο κώδικα και αντί να κάνουμε import τη lib και να καλούμε πχ την lib.digit_mean_plot() καλούμε σκέτο digit_mean_plot().

**Comment by georgepar** [comment]
Θέλουμε να στείλετε ότι χρειάζεται για να τρέξουν **όλα** τα ερωτήματα της εργασίας. Αν τα έχετε βάλει όλα σε ένα δικό σας σκριπτ δεν έχουμε πρόβλημα.
