### ISSUE TITLE
Ερώτηση για τη πρόοδο 

### ISSUE THREAD

**Issue by ylefen** [slp-ntua/patrec-labs#106]
Καλησπέρα, 

Όσον αφορα την αυριανή πρόοδο: 

1) Αν δεν παρευρεθούμε (παρόλο που εχουμε δηλώσει στο helios) θεωρείτε ότι παίρνουμε 0 και εξεταζόμαστε στα 3 στην τελική εξέταση ή παμε κατ ευθείαν για 5 στην τελική εξέταση; 

2) Σε περίπτωση που ο βαθμος της πρόοδου δεν είναι ευνοϊκός γίνεται να κρατηθεί το max { προοδος + τελικη + ασκησεις, τελικη + ασκησεις} ; 

Ευχαριστώ εκ των προτέρων

**Comment by efthymisgeo** [comment]
Η πρόοδος ΔΕΝ είναι υποχρεωτική. Εάν δεν δώσετε γράφετε με άριστα το 10 στο τέλος. Εάν δώσετε υπάρχει συμψηφισμός και κρατάμε το μέγιστο. Δείτε σας παρακαλώ και το βαθμολογικό σχήμα στη σελίδα του μαθήματος.

**Comment by dkoun** [comment]
καλησπέρα , είμαστε μερικά άτομα που δηλώσαμε χθες το απόγευμα για την πρόοδο και δεν είμαστε στην κατανομή , γινεται να συμμετέχουμε κανονικα κι εμεις?

> Η πρόοδος ΔΕΝ είναι υποχρεωτική. Εάν δεν δώσετε γράφετε με άριστα το 10 στο τέλος. Εάν δώσετε υπάρχει συμψηφισμός και κρατάμε το μέγιστο. Δείτε σας παρακαλώ και το βαθμολογικό σχήμα στη σελίδα του μαθήματος.

καλησπέρα , είμαστε κάποια άτομα που δηλώσαμε χθες το απόγευμα και δεν συμπεριλαβανόμαστε στην κατανομή , γίνεται να συμμετάσχουμε κι εμε΄ς κανονικά ? Δεν γνωρίζαμε μέχρι πότε έπρεπε να δηλώσουμε οπότε θέλαμε να δουμε πως θα πάει το διάβασμα.
