### ISSUE TITLE
Ημερομηνια παράδοσης 1ης Σειράς Αναλυτικών Ασκήσεων

### ISSUE THREAD

**Issue by DimLiak** [slp-ntua/patrec-labs#107]
Καλησπέρα σας, σε μια απο τις προσφατες ανακοινώσεις που είχαν γίνει στην ιστοσελίδα του μαθήματος μας ενημερώσατε ότι η παράδοση της 1ης Σιεράς των Αναλυτικών Ασκήσεων πήρε παράταση μέχρι την Κυρικαή 28/11. Ωστόσο στην ιστοσελίδα του μαθήματος εμενά προσωπικά δεν μου φαίνεται η αλλαγή στην ημερομηνία παράδοσης και φάινεται σαν να είναι εκπρόθεσμη η παράδοση σε αυτό το σημείο. Ενδέχεται να γίνει η αλλαγή της ημερομηνίας ή θα την παραδώσουμε ως έχει και θα φαίνεται σαν εκπρόθεσμη?

**Comment by georgepar** [comment]
Fixed
