### ISSUE TITLE
Ερωτηση για το 4ο βημα της προπαρασκευαστικης

### ISSUE THREAD

**Issue by yasonkal** [slp-ntua/patrec-labs#109]
Στο 4ο βημα λετε: "Αναπαραστήστε τα ιστογράμματα του 1ου και του 2ου MFCC των ψηφίων n1 και n2 (βλέπε ΣΗΜΕΙΩΣΗ) για
όλες τους τις εκφωνήσεις. Πόση απόκλιση υπάρχει?". Θελετε να κανουμε ενα histogram για καθε ενα απο τα 2 πρωτα mfcc του καθε
enunciation (δηλ. καθε εκφωνησης του ψηφιου n1 και του ψηφιου n2); **ή** 4 ιστογραμματα, 1 απο ολα τα πρωτα mfcc των εκφωνησεων του πρωτου ψηφιου (n1), 1 ομοιως ολων των δευτερων mfcc των εκφωνησεων του πρωτου ψηφιου και αλλα 2 αντιστοιχα του δευτερου ψηφιου (n2);

**Comment by georgepar** [comment]
4 ιστογράμματα. Ο στόχος είναι να δείτε γρήγορα εποπτικά αν μπορεί να διαχωριστεί το n1 από το n2 με βάση αυτό το feature,
