### ISSUE TITLE
Διευκρίνηση για εναλλαγή συμβώλων στην scatterplot - Βήμα 5 - Lab2

### ISSUE THREAD

**Issue by dimisarantidis** [slp-ntua/patrec-labs#110]
Στο Βήμα 5 με πιό κριτήριο θέλετε να αλλάζει το σύμβολο που αντιστοιχεί σε κάθε δείγμα? Θα μπορούσε πχ να αλλάζει ανα ψηφίο ή ανα εκφωνητή κτλ. 

Σε περίπτωση που είναι ανα ψηφίο η αλλαγή, γιατι θέλουμε να αλλάζει και το σχήμα και το χρώμα της απεικόνησης κάθε δείγματος?

**Comment by georgepar** [comment]
χρωμα -> ψηφίο 
συμβολο -> εκφωνητή

ή το ανάποδο.

**Comment by dimisarantidis** [comment]
Thanks
