### ISSUE TITLE
2η Ερωτηση για το 4ο ερωτημα της προπαρ.

### ISSUE THREAD

**Issue by yasonkal** [slp-ntua/patrec-labs#111]
Στην εκφωνηση λεει "Αναπαραστήστε γραφικά τη συσχέτιση των MFSCs για την κάθε
εκφώνηση". Μπορειτε να εξηγησετε τι εννοειτε συσχετιση των MFSC;

**Comment by georgepar** [comment]
Εννοούμε να υπολογίσετε τον πίνακα συσχετισης (hint https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html)

Μεταξύ του 1ου, 2ου, 3ου ... MFSC

**Comment by yasonkal** [comment]
δηλαδη με λιγα λογια ολους τους πιθανους συνδυασμους, το 1ο με το 2ο,3ο,4ο, μετα το 2ο με το 3ο,4ο κ.ο.κ, ετσι;

**Comment by georgepar** [comment]
ναι
