### ISSUE TITLE
Απορία πάνω στα διανύσματα του ερωτήματος 5 της προπαρασκευής

### ISSUE THREAD

**Issue by LefterisLymp** [slp-ntua/patrec-labs#112]
Καλησπέρα σας,
Στο ερώτημα 5 ζητείται να απεικονίσουμε δύο διανύσματα που θα έχει το ένα τις μέσες τιμές και το άλλο τις αποκλίσεις ή θα πρέπει αυτά τα δύο να είναι concatenated σε ένα διάνυσμα;

**Comment by georgepar** [comment]
2 ξεχωριστα

**Comment by LefterisLymp** [comment]
Ευχαριστώ πολύ!
