### ISSUE TITLE
Απορία στα δεδομένα του ερωτήματος 7 της προπαρασκευής

### ISSUE THREAD

**Issue by LefterisLymp** [slp-ntua/patrec-labs#113]
Στο ερώτημα 7, τα δεδομένα που θα χρησιμοποιήσουμε θα είναι τα διανύσματα με τις mfcc τιμές μόνο ή τα concatenated διανύσματα που φτιάξαμε στο ερώτημα 5;

**Comment by georgepar** [comment]
Μπορείτε να κάνετε πειράματα με διαφορετικά features για να δείτε ποια επηρεάζουν περισσότερο την απόδοση του μοντελου

**Comment by LefterisLymp** [comment]
Εντάξει σας ευχαριστώ!
