### ISSUE TITLE
Ερωτ. για το 5ο βημα

### ISSUE THREAD

**Issue by yasonkal** [slp-ntua/patrec-labs#114]
Λετε: "Αναπαραστήστε με scatter plot τις 2 πρώτες διαστάσεις των διανυσμάτων αυτών, χρησιμοποιώντας διαφορετικό
χρώμα και σύμβολο για κάθε ψηφίο. Σχολιάστε το διάγραμμα." Εννοειτε 2 διαγραμματα, οπου στον εναν αξονα μπαινει η πρωτη διασταση του mean και στον αλλον η δευτερη του mean και ομοιως στο διαγραμμα του standard deviation, ή 1 διαγραμμα οπου ο ενας αξονας ειναι η πρωτη διασταση του mean και ο αλλος η πρωτη διασταση του standard deviation;

**Comment by georgepar** [comment]
Προτιμούμε ξεχωριστά διαγράμματα για το mean και το std
