### ISSUE TITLE
Βημα 4-Ιστογραμματα

### ISSUE THREAD

**Issue by mpektkd** [slp-ntua/patrec-labs#116]
Ηθελα να ρωτησω για το ερωτημα 4, καθως λαμβανουμε τα παρακατω ιστογραμματα. 
![image](https://user-images.githubusercontent.com/62422421/145080798-8fc4aab3-b7a6-44ce-9671-fb00623afd18.png)
![image](https://user-images.githubusercontent.com/62422421/145080858-2e58bea6-a462-4128-a092-a371d656fa38.png)

Κι για τα δυο ψηφια(n1=6, n2=9), λαμβανουμε τιμες γυρω απο το μηδεν κι για τους δυο ομιλητες. Παρατηρουμε οτι, διαφερουν στον αριθμο των bins γυρω απο το μηδεν αλλα το γεγονος οτι, περικλειονται γυρω απο κει χωρις καμια αλλη διαφροποιηση με προβληματιζει κι θα ηθελα να ξερω αν παει κατι λαθος.

Να σημειωσω οτι καλουμε την plt.hist(), με bins='auto'.

**Comment by efthymisgeo** [comment]
Δοκίμασε μια με fixed αριθμό bins

**Comment by mpektkd** [comment]
![image](https://user-images.githubusercontent.com/62422421/145430430-58c429d7-bb20-47da-9138-def8145b72bc.png)
![image](https://user-images.githubusercontent.com/62422421/145430462-de038444-866d-4e07-85c8-a0628da64c04.png)
![image](https://user-images.githubusercontent.com/62422421/145430522-f7e44fb0-5358-4b49-8dbb-4b61a16b8860.png)

Δοκιμασα με τιμες στο ευρος [-700,500] ανα 100, και παλι γυρω απο το μηδεβν συγκεντρώνεται η πληροφορια. Νομιζω, δεν ειμαι σιγουρος αν εχω καταλαβει καλα, τι ζητειται να παρατηρησουμε.
