### ISSUE TITLE
Ερώτημα 7

### ISSUE THREAD

**Issue by tommyshelby4** [slp-ntua/patrec-labs#118]
Έχετε δώσει έτοιμη συνάρτηση που κάνει το split, ωστόσο εκτός από train και test γυρνάει και δύο πίνακες ακόμα. Επίσης στο labels τι πρέπει να βάλουμε για να δουλέψει σωστά? Επίσης θα περάσουμε ως features στο ερώτημα αυτό μόνο τα MFCCs ή και τις παραγώγους τους?

**Comment by georgepar** [comment]
> Έχετε δώσει έτοιμη συνάρτηση που κάνει το split, ωστόσο εκτός από train και test γυρνάει και δύο πίνακες ακόμα. 

Υποθέτω εννοείς [αυτή τη συνάρτηση](https://github.com/slp-ntua/patrec-labs/blob/main/lab2/parser.py#L51), η οποία γυρνάει τα εξης 

```
X_train : [N,F] features για τα δείγματα εκπαίδευσης 
X_test: [M,F] features για τα δείγματα αποτίμησης 
y_train: [N] labels για τα δείγματα εκπαίδευσης. Ένα προς ένα αντιστοιχία με τις γραμμές του X_train
y_test: [M] labels για τα δείγματα αποτίμησης. Ένα προς ένα αντιστοιχία με τις γραμμές του X_test
spk_train: [N] ο ομιλητής που εκφωνει το δείγμα. Ένα προς ένα αντιστοιχία με τις γραμμές του X_train
 spk_test: [Μ] ο ομιλητής που εκφωνει το δείγμα. Ένα προς ένα αντιστοιχία με τις γραμμές του X_test
```


> Επίσης θα περάσουμε ως features στο ερώτημα αυτό μόνο τα MFCCs ή και τις παραγώγους τους?

Mfcc + deltas (παραγωγοι)

> Επίσης στο labels τι πρέπει να βάλουμε για να δουλέψει σωστά? 

Δεν καταλαβαίνω την ερώτηση
