### ISSUE TITLE
Βήματα 9 & 10

### ISSUE THREAD

**Issue by Mix-Stef** [slp-ntua/patrec-labs#119]
Στο βήμα 9 πηγαίνουμε στο link της εκφώνησης, στον φάκελο recordings και αυτά τελικά θα είναι τα νέα wavs; Θα πρέπει να χρησιμοποιήσουμε τι συναρτήσεις του φακέλου acquire_data; Επίσης αν μπω στον φάκελο recordings τότε μου βγάζει το εξής μήνυμα : Sorry, we had to truncate this directory to 1,000 files. 2,000 entries were omitted from the list. Πώς μπορώ αυτόματα να κατεβάσω όλα τα wavs;

Στο βήμα 10:

1) τα μη-μηδενικά στοιχεία του πίνακα μεταβάσεων αρχικοποιούνται τυχαία;
2) Το διάνυσμα end πώς αρχικοποιείται;
3) Το διάνυσμα Χ είναι μόνο εκείνα τα features των wavs που έχουν label ίσο με το εκάστοτε ψηφίο, ενώ η δομή data περιλαμβάνει όλα τα wavs (τα features τους δηλαδή) ;

**Comment by tommyshelby4** [comment]
εγω επειδη το εκανα θα σου προτεινα να κανεις απλα clone ολο το repo, και μετα απλα να χρησιμοποιησεις την parser για να διαβασεις τα δεδομενα απο τον φακελο recordings, η acquire data δε χρειαζεται

**Comment by georgepar** [comment]
Όπως είπε ο συνάδελφος

**Comment by GeorgiosPapadakis** [comment]
Πως μπορούμε να κάνουμε clone το repo ?
