### ISSUE TITLE
Βημα 8

### ISSUE THREAD

**Issue by iliaskoum** [slp-ntua/patrec-labs#122]
τα sin που θελουμε για αυτο το ερωτημα ειναι αυτης της μορφης?
![image](https://user-images.githubusercontent.com/86619354/145688859-a3e9bfc6-1d31-4855-8652-c255e8e090a2.png)

**Comment by georgepar** [comment]
Looks good to me. Απλά θα πρέπει  να φτιάξετε πολλές διαφορετικές ακολουθίες
