### ISSUE TITLE
Ερώτηση(εις) σχετικά με GMM-HMM

### ISSUE THREAD

**Issue by knasiotis** [slp-ntua/patrec-labs#123]
Θέλω να κάνω μερικές ερωτήσεις σχετικά με το HMM.py βοηθητικό κώδικα.

- `X = [] # data from a single digit (can be a numpy array)` Εδώ εννοείτε από ένα μεμονωμένο ψηφίο ή για όλα τα ψηφία ενός label λ.χ του ψηφίου '1'
- `data = [] # your data: must be a Python list that contains: 2D lists with the sequences (so its dimension would be num_sequences x seq_length x feature_dimension)
            # But be careful, it is not a numpy array, it is a Python list (so each sequence can have different length)` To num_sequences παραπέμπει στον αριθμό των frames για κάθε digit και το feature dimension στα MFCCs κάθε digit;
- To starting probability matrix είναι δισδιάστατο;
- Ο πίνακας μεταβάσεων έχει συνολικές διαστάσεις ij όπου i είναι ο αριθμός των frames και j ο αριθμός των MFCCs;
- Το π_i τι συνολική διάσταση έχει; όσα και τα MFCCs;
- Τα ending probability matrix πως ορίζεται; Δεν αναφέρεται κάτι στην εκφώνηση.

**Comment by georgepar** [comment]
> X = [] # data from a single digit (can be a numpy array) Εδώ εννοείτε από ένα μεμονωμένο ψηφίο ή για όλα τα ψηφία ενός label λ.χ του ψηφίου '1'

Εδώ βάζετε όλα τα δειγματα (ακολουθιες) που αντιστοιχούν σε ένα ψηφιο (πχ το 0)

> data = [] # your data: must be a Python list that contains: 2D lists with the sequences (so its dimension would be num_sequences x seq_length x feature_dimension) # But be careful, it is not a numpy array, it is a Python list (so each sequence can have different length) To num_sequences παραπέμπει στον αριθμό των frames για κάθε digit και το feature dimension στα MFCCs κάθε digit;

* num_sequences είναι ο αριθμός των δειγμάτων (ακολουθιων)
* seq_length ειναι το μήκος της κάθε ακολουθίας (αριθμός  των frames)
* feature_dimension ειναι ο αριθμός των χαρακτηριστικων 

> To starting probability matrix είναι δισδιάστατο; Το π_i τι συνολική διάσταση έχει; όσα και τα MFCCs;

Το starting probability δίνει μια αρχικη πιθανότητα σε καθε κατάσταση οπότε είναι μονοδιάστατο με διάσταση τον αριθμό των καταστάσεων 

> Ο πίνακας μεταβάσεων έχει συνολικές διαστάσεις ij όπου i είναι ο αριθμός των frames και j ο αριθμός των MFCCs;

Όχι. Ο πίνακας μεταβάσεων περιγράφει την πιθανότητα να πάμε από τη μια κατάσταση του hmm στην άλλη, οπότε έχει διαστάσεις SxS όπου S ο αριθμός των καταστάσεων.


> Τα ending probability matrix πως ορίζεται; Δεν αναφέρεται κάτι στην εκφώνηση.

Ο πίνακας αυτός λέει σε ποιες καταστάσεις μπορεί να καταλήξει το hmm. Εφόσον ζητάμε left to right,  θες πάντα να τελειώνει στην τελική κατάσταση. Αν το σκεφτείς σαν αυτόματο, αυτός ο πίνακας σου ορίζει τις καταστάσεις  αποδοχής.

Γενικά νομίζω το μπέρδεμα εδώ γίνεται επειδή προσπαθείς να αποδόσεις φυσική σημασία στις καταστάσεις του hmm. Αυτές οι καταστάσεις είναι κρυφές καθώς αντιστοιχούν σε πράγματα που δε θέλουμε να κάτσουμε να τα μοντελοποιησουμε αναλυτικά. Πιο πολύ βοηθά να τις σκέφτεσαι ότι αντιστοιχούν σε κάτι σαν "φωνηματα" η δομικές μονάδες φωνής.

Οπότε ουσιαστικά αυτό που κάνεις είναι να δίνεις στο μοντέλο ένα αριθμό εσωτερικών καταστάσεων και μια γενικη δομή μέσω των π, transition matrix και των τελικών καταστάσεων.

Αν χρειαστείς κάποια παραπάνω διευκρίνηση μπορείς να ρωτήσεις και θα πρότεινα και μια ανάγνωση στο αντίστοιχο κεφάλαιο του bishop

**Comment by knasiotis** [comment]
> Ο πίνακας αυτός λέει σε ποιες καταστάσεις μπορεί να καταλήξει το hmm. Εφόσον ζητάμε left to right, θες πάντα να τελειώνει στην τελική κατάσταση. Αν το σκεφτείς σαν αυτόματο, αυτός ο πίνακας σου ορίζει τις καταστάσεις **αποδοχής**
Δηλαδή για 2 states, ειναι [0.0, 1.0];

**Comment by georgepar** [comment]
Ναι

**Comment by knasiotis** [comment]
Συγγνώμη και πάλι για την ενόχληση,
Δίνω στο `a = GeneralMixtureModel.from_samples(MultivariateGaussianDistribution, n_mixtures, X)` X ακολουθίες, ας αυτές για το ψηφίο '0' διαστάσεων (x,13) είτε ως ndarray είτε ως λίστα και μου βγάζει 

> ValueError: must pass in at least two distributions

**Comment by tommyshelby4** [comment]
εγω εδω παραπανω δεν καταλαβα ποια η διαφορα που πινακα data με τον Χ. Ο Χ θα εχει ειπαμε ολα τα instances ενος ψηφιου καθε φορα, πχ. 0, άρα διασταση numberOfDigits*numFrames(seqLebgth δηλαδη)*13, o data τι διαφορά έχει?

**Comment by georgepar** [comment]
> εγω εδω παραπανω δεν καταλαβα ποια η διαφορα που πινακα data με τον Χ. Ο Χ θα εχει ειπαμε ολα τα instances ενος ψηφιου καθε φορα, πχ. 0, άρα διασταση numberOfDigits*numFrames(seqLebgth δηλαδη)*13, o data τι διαφορά έχει?

Ο x δεν περιέχει ακολουθίες. Περιέχει flat όλα τα frames όλων των εκφωνήσεων ενός ψηφίου. Δηλαδή είναι δισδιάστατος πίνακας  (n_samples * n_frames, n_features).

**Comment by georgepar** [comment]
> Δίνω στο a = GeneralMixtureModel.from_samples(MultivariateGaussianDistribution, n_mixtures, X) X ακολουθίες, ας πούμε αυτές για το ψηφίο '0' διαστάσεων (x,13) είτε ως ndarray είτε ως λίστα και μου βγάζει

Θα σου πρότεινα να δεις το documentation page του pomegranate που είναι αρκετά αναλυτικό (https://pomegranate.readthedocs.io/en/latest/GeneralMixtureModel.html)


> Επίσης το sample που θα τρέξουμε viterbi έχει διαστάσεις n_frames x n_mfccs;

Σκέψου για ποιο λόγο τρέχουμε viterbi? δηλαδή τι μας δίνεται στην είσοδο (ακολουθία παρατηρήσεων) και τι βγαίνει στην έξοδο (ακολουθία καταστάσεων
