### ISSUE TITLE
Βήμα 10: Σφάλμα στην GeneralMixtureModel.from_samples

### ISSUE THREAD

**Issue by Chrz95** [slp-ntua/patrec-labs#125]
Όταν εκτελώ στην συνάρτηση αυτή, που πετάει το σφάλμα 

 **File "pomegranate\gmm.pyx", line 534, in pomegranate.gmm.GeneralMixtureModel.from_samples
ValueError: need more than 1 value to unpack**

Το έψαξα και υποπτεύομαι οτι φταίει κάτι στην έκδοση των modules. Μπορείτε να μας πείτε ποια πακέτα και ποιες εκδόσεις να χρησιμοποιήσουμε για να φτιάξουμε ένα virtual env, όπως μας είχατε πει στο εργαστήριο ; 

Επίσης, αν είναι εύκολο να ανεβούν τα jupyter notebooks που δείξατε στο εργαστήριο; 

Ευχαριστώ πολύ

**Comment by georgepar** [comment]
https://github.com/slp-ntua/patrec-labs/issues/44

Το κάνω reopen και pin

**Comment by georgepar** [comment]
Όλο το υλικό του εργαστηρίου θα ανέβει

**Comment by iliaspap** [comment]
Καλησπέρα.
 Κι εμείς είχαμε το ίδιο πρόβλημα, το οποίο διορθώθηκε μετά την αλλαγή των εκδόσεων. Όμως προέκυψε ένα άλλο error στην κλήση της ίδιας συνάρτησης, στο οποίο φαίνεται ότι το πρόγραμμα μεταχειρίζεται τα δεδομένα Χ (για ένα συγκεκριμένο ψηφίο) σαν numpy.array. Κι εσείς γράφετε στον βοηθητικό κώδικα "(can be a numpy array)". Όμως το Χ δεν περιέχει τα χαρακτηριστικά για το συγκεκριμένο ψηφίο για κάθε εκφώνηση; Το πλήθος των frames άρα και το shape των features δε διαφέρουν από εκφώνηση σε εκφώνηση; Πώς θα μπορούσε ο Χ να μετατραπεί σε numpy array;
Ευχαριστώ

**Comment by christinakiii** [comment]
Θα ηθελα να κανω μια συμπληρωματικη ερωτηση για το βημα 10:
εγκαθιστώντας τα πακέτα όπως ειπατε στο #44 προκυπτει το εξης θεμα: οταν κανω pip install numba==0.48 φαινεται σαν το 
numba.decorators να μην υπαρχει. το οποιο χρησιμοποιει η librosa. και σταματησε να λειτουργει ολος ο κωδικας....

**Comment by georgepar** [comment]
pip install numba==0.48
pip install librosa==0.6.3

--> solution: install numba first

**Comment by georgepar** [comment]
> Όμως το Χ δεν περιέχει τα χαρακτηριστικά για το συγκεκριμένο ψηφίο για κάθε εκφώνηση; Το πλήθος των frames άρα και το shape των features δε διαφέρουν από εκφώνηση σε εκφώνηση; Πώς θα μπορούσε ο Χ να μετατραπεί σε numpy array;

Το X δεν περιέχει ακολουθίες, περιέχει τα individual frames. Οπότε είναι ένας δισδιάστατος πίνακας ο οποίος περιέχει όλα τα frames από όλα τα δείγματα του dataset χωρίς να σε νοιάζει η σειρά.

**Comment by christinakiii** [comment]
> pip install numba==0.48 pip install librosa==0.6.3
> 
> --> solution: install numba first
> 
> _Originally posted by @phamdanglam1986 in [librosa/librosa#1160 (comment)](https://github.com/librosa/librosa/issues/1160#issuecomment-691542446)_

δεν μου επιτρεπει ξανα την εγκατασταση του numba

cannot import name 'InvalidSchemeCombination' from 'pip._internal.exceptions' (C:\Users\user\anaconda3\lib\site-packages\pip\_internal\exceptions.py
