### ISSUE TITLE
Βήμα 10: Ερώτηση για τα δεδομένα εισόδου

### ISSUE THREAD

**Issue by mmantalos** [slp-ntua/patrec-labs#126]
Στο Βήμα 10, για την συνάρτηση from_samples(), τα δεδομένα Χ τι μορφή πρέπει να έχουν;
Το documentation λέει πως έχει shape (n_samples, n_dimension) αλλά τα δεδομένα που μας επιστρέφει ο parser είναι μία λίστα από  2d np.arrays() διαφορετικού μεγάθους το καθένα. Στην μορφή που μας δίνονται η συνάρτηση βγάζει error, πρέπει να τα μετασχηματίσουμε κάπως;

**Comment by efthymisgeo** [comment]
Κάνε ένα screenshot τι σου επιστρεφει ακριβώς. Μήκος λίστας, διαστάσεις κάθε item της λίστας κλπ

**Comment by mmantalos** [comment]
![image](https://user-images.githubusercontent.com/44544579/146035421-cf361dd2-8e08-4c60-9403-e6da666009d5.png)
Τα X_train και y_train τα έχουμε πάρει κατευθείαν από τον parser. Το X_train είναι μία λίστα από np.arrays με shapes που φαίνονται στην εικόνα. Καταλάβαμε πως στην GeneralMixtureModel.from_samples() έπρεπε να δώσουμε τα X_train για κάποιο συγκεκριμένο ψηφίο (πχ το 1). Αυτό όμως φαίνεται πως δεν έχει τη μορφή που θέλει η συνάρτηση. Σκεφτήκαμε να τα κάνουμε np.array αλλά κάθε δεδομένο έχει διαφορετικό μέγεθος.
