### ISSUE TITLE
Βήμα 10

### ISSUE THREAD

**Issue by Chrz95** [slp-ntua/patrec-labs#127]
Στο βήμα 10, τι τιμές log likelihood αναμένουμε; Σε εμένα προκύπτουν μεγάλες αρνητικές τιμες (πχ -302.275057450546, -239.61760105008838 κτλπ) , το οποίο σημαίνει οτι η αντιστοιχη likelihood είναι πάρα πολυ κοντά στο 0, ενώ θα ανέμενα να είναι κοντά στο 1. Εχω εισάγει τα δεδομένα ως εξης :

 Χ = total number of frames for this digit from all its files* n_features (numpy array) 
data = n_files (of the specific digit) *n*frames*n_features (3D list of lists)
sample = data[0]

που με βάσει τις απαντήσεις που έχω διαβάσει και την εκφώνηση, νομίζω είναι σωστό. 

Έχετε κάποια άποψη για το τι κάνω λάθος; Εχω δοκιμάσει διάφορες τιμες n_states, n_mixtures, trans_mat, με το ίδιο αποτέλεσμα.

**Comment by efthymisgeo** [comment]
Ως προς μετρικές όπως το accuracy πως πας?

**Comment by efthymisgeo** [comment]
Επίσης σε ποια συνάρτηση ακριβώς έχεις εισάγει τα δεδομένα όπως λες? Επιπλέον θα ήθελα να μου γράψεις και τις διαστάσεις των πινάκων λιστών είτε με ένα screenshot είτε σαν
```
X.shape = (a, b)

where a: ----- and b: ----- 
```

**Comment by Chrz95** [comment]
Το Χ στην GeneralMixtureModel.from_samples και το data HiddenMarkovModel.from_matrix.
To X έχει shape (αριθμός παραθύρων εκφώνησεων ψηφίου ι,13) (numpy array) και το data (3Δ list) (αριθμός εκφώνησεων ψηφίου ι,αριθμός παραθυρων (frames) εκφώνησης ,13) . Είμαι στο βήμα 10, δηλαδή την κατασκευή του GMM-HMM (hmm.py) για κάθε ψηφίο και δεν έχω προχωρήσει στον υπολογισμό accuracy, επειδή θεώρησα ότι το log probability που δίνει το Viterbi είναι λάθος και ότι θα πρέπει θα δίνει τιμές κοντά στο 0.
