### ISSUE TITLE
Αδυναμία υποβολής 2ης εργαστηριακής Helios

### ISSUE THREAD

**Issue by Tsaousis** [slp-ntua/patrec-labs#132]
Προσπαθούμε να υποβάλλουμε την δεύτερη εργαστηριακή στο helios την τελευταία μισή ώρα και ενώ φαίνεται οτι δέχεται την υποβολή, τελικά δεν ανεβαίνει. Προσπάθησε και ο συνεργάτης μου και έχει το ίδιο πρόβλημα.

**Comment by Costopoulos** [comment]
Εντάξει, μόλις καταφέραμε να υποβάλουμε. Κλείστε το issue αν δεν υπάρχει κι άλλος με το ίδιο πρόβλημα.
