### ISSUE TITLE
2η αναλυτική σειρά Αναγνώρισης προτύπων

### ISSUE THREAD

**Issue by dkoun** [slp-ntua/patrec-labs#135]
Καλησπέρα και καλή χρονιά,
Για την 2η αναλυτική σειρά μπορούμε να χρησιμοποιήσουμε όπου μας βολεύει python για επιλύσεις και για σχεδίαση γραφημάτων στις ασκήσεις ; Αν ναι θέλετε να παραθέσουμε και τον κώδικα ή μόνο εικόνες και αποτελέσματα καθώς ζητείται ένα pdf ως παραδοτέο;

**Comment by georgepar** [comment]
μπορείτε να χρησιμοποιήσετε ότι εργαλείο χρειάζεστε. Τον κώδικα μπορείτε να τον παραθέσετε σε ένα appendix στο τέλος του pdf.
