### ISSUE TITLE
Ενδεχόμενο παράτασης 2ης Σειράς Αναλυτικών Ασκήσεων

### ISSUE THREAD

**Issue by johnliak** [slp-ntua/patrec-labs#136]
Καλησπέρα, θα μπορούσε να δοθεί μία παράταση για τη 2η σειρά αναλυτικών ασκήσεων για να προλάβουμε, λόγω και μεγάλου φόρτου εργασιών, να απαντήσουμε όσο το δυνατόν περισσότερα ερωτήματα;

**Comment by StefanosVks7** [comment]
+1

**Comment by dimitrismit** [comment]
+1
