### ISSUE TITLE
Lab 3 - New code vs Old code

### ISSUE THREAD

**Issue by srigas** [slp-ntua/patrec-labs#139]
Edited αφότου φάνηκε πιο ξεκάθαρα το πρόβλημα:

Καλησπέρα,

Σε ό,τι αφορά το helper code για το Lab 3, ο κώδικας στο dataset.py του GitHub διαφέρει από τον κώδικα που δίνεται [εδώ](https://www.kaggle.com/c/multitask-affective-music-lab-2022/code) στο Kaggle. Για παράδειγμα, στον κώδικα του GitHub δε γίνεται διάκριση μεταξύ mel/chroma/fused κατά το reading των δεδομένων και λαμβάνονται υπ' όψιν μόνο τα fused. Προφανώς, οι έτοιμες υλοποιήσεις θέλουν κάποια επιπλέον tweaks πέρα από τα αναγραφόμενα TODOs (αντίστοιχο πρόβλημα προκύπτει και στον κώδικα του LSTM).

Το βασικό ζήτημα είναι πως ο κώδικας του GitHub που αφορά συγκεκριμένα την SpectrogramDataset οδηγεί σε προβλήματα κατά τη μεταφόρτωση των beat-synced δεδομένων. Συγκεκριμένα, η κλάση (ορθώς) διαβάζει το αρχείο train_labels.txt από το directory .../fma_genre_spectrograms_beat και ορθώς εντοπίζει αρχεία της μορφής ΧΧΧΧ.beatsync.fused.npy

Αυτό όμως οδηγεί στο κάτωθι error:

> No such file or directory: '../input/patreco3-multitask-affective-music/data/fma_genre_spectrograms_beat/train/XXXX.beatsync.fused.npy'

Παραδόξως, αν στο ίδιο directory αναζητήσουμε αρχεία της μορφής που έχουν στο non-beat directory, δηλαδή αρχεία της μορφής ΧΧΧΧ.fused.full.npy, τότε διαβάζονται κανονικά. Ακόμα και "με το μάτι" στο Kaggle φαίνεται πως στο _beat directory οι καταλήξεις έχουν τη μορφή "beatsync.fused.npy" παρ' όλα αυτά για κάποιο λόγο δεν αναγνωρίζονται.

**Comment by srigas** [comment]
Αν κάνουμε hardcode το .txt που διαβάζει η συνάρτηση όπως φαίνεται στην εικόνα, διαβάζονται σωστά και τα non-beat-synced, και τα beat-synced. Παρότι είναι εντελώς παράλογο, μιας και βλέπουμε (κυριολεκτικά) πως στον φάκελο _beat υπάρχουν αρχεία της μορφής XXXX.beatsync.fused.npy.

![Screenshot_4](https://user-images.githubusercontent.com/70939180/149225142-aed5bf90-5e80-4687-8008-f04543dfe32d.png)

**Comment by knasiotis** [comment]
Έχω το ίδιο ακριβώς πρόβλημα. Ενώ όλα τα δεδομένα φαίνονται στον explorer του kernel, τα έχει αναγνωρίσει όλα ως .fused.full.

**Comment by georgepar** [comment]
Μπορείτε να διαβάσετε ένα από τα αρχεία στο φάκελο fma_genre_spectrograms_beat και να τυπώσετε ιτς διαστάσεις του πίνακα?

**Comment by srigas** [comment]
Ναι, αυτό λέω, μια χαρά διαβάζονται και είναι και σωστά γιατί τα beat έχουν πολύ λιγότερα timesteps. Απλά αναφέρομαι στο κομμάτι του naming, λέγοντας πως τα αρχεία διαβάζονται με τον κώδικα που έχω επισυνάψει στο 2ο σχόλιο και όχι με τον κώδικα της SpectrogramDataset που υπάρχει στο GitHub. Και αυτό επειδή η κλάση του GitHub ψάχνει αρχεία με την επέκταση "beatsync.fused".

Να πω πάντως ότι στην παραπάνω εικόνα, ναι μεν φαίνεται να υπάρχουν φάκελοι με την επέκταση "beatsync.fused", αλλά από κάτω γράφει Empty. Ίσως εκεί να έχει συμβεί κάτι, γιατί κατά τ' άλλα ούτε εμένα μου βγάζει νόημα το να τα βλέπω με τα μάτια μου στο directory, αλλά η Python να μου λέει ότι δεν υπάρχει τίποτα.

**Comment by georgepar** [comment]
Μπορείς να αλλάξεις το beatsynced σε full και θα πρέπει να παίξει απροβλημάτιστα. Το empty στο kaggle το βλέπεις επειδή το kaggle δεν αναγνωρίζει σωστα το filetype.

Λογικά είναι κάποιο θέμα versioning του dataset. Δε θα έπρεπε να επηρρεάζει πέρα από αυτή τη μικρή αλλαγή.

**Comment by srigas** [comment]
Έχουν τρέξει όλα χωρίς θέμα με την αντικατάσταση που προτείνω στο δεύτερο σχόλιο, η οποία στην ουσία φροντίζει παντού να έχουμε "fused.full" extension. Το αναφέρω απλά για να υπάρχει υπ' όψιν ως θέμα και να διευκολυνθεί όποι@ άλλος πάει να το τρέξει και βρίσκει παρόμοιο error :)
