### ISSUE TITLE
[Evaluators of Classifiers]

### ISSUE THREAD

**Issue by Mavrepis** [slp-ntua/patrec-labs#14]
Καλησπέρα, 

Για όλες τις μεθόδους τύπου evaluate_classifier δίνεται μέθοδος με παραμέτρους X,y, ενώ ζητείται να γίνεται και η δημιουργία του ταξινομητή μεσα στην εν λόγω μέθοδο ( που προϋποθέτει fit ). Επειδή δεν αναγράφεται κάτι στο docsting θέλετε να θεωρήσουμε ότι τα X,y που περνάμε είναι το σύνολο των δεδομένων και μέσα σε κάθε τέτοια μέθοδο να κάνουμε train/test split ή μπορούμε απλώς να αλλάξουμε τις παραμέτρους και να περνάμε X_train,y_train,X_test,y_test;

**Comment by georgepar** [comment]
Μην αλλάξετε τις παραμέτρους. Αυτές οι συναρτήσεις λέμε ότι καλούν την `evaluate_classifier` η οποία κάνει cross-validation.
Δείτε λίγο προσεκτικά τα docstrings.
