### ISSUE TITLE
Βαθμολογικό πέναλτι/2η σειρά αναλυτικών ασκήσεων

### ISSUE THREAD

**Issue by Evangelia0** [slp-ntua/patrec-labs#140]
Υπάρχει η δυνατότητα να παραδώσεις εκπρόθεσμα τη 2η σειρά αναλυτικών ασκήσεων με βαθμολογικό  πέναλτι 10% όπως γίνεται και στην παράδοση εργαστηριακών ασκήσεων ;

**Comment by georgepar** [comment]
Στείλε μου με ένα mail.

**Comment by lole32** [comment]
Καλησπέρα !

έχω το ίδιο θέμα , μόνο που την εργασία την είχα έτοιμη από τις 12 του μηνός, απλά θεωρούσα ότι η υποβολή θα είναι ανοιχτή μέχρι 13 βράδυ (όπως και στις υπόλοιπες εργασίες) γι' αυτό και καθυστέρησα . Εν ολίγοις την έχω ανεβάσει εκ πρόθεσμα (15 ώρες μετά την λήξη) . Σας έχω στείλει και email . 
Τι γίνεται σε αυτή την περίπτωση ; Υπάρχει βαθμολογικό πέναλτι ;
