### ISSUE TITLE
Βήμα 6: Τιμές μετρικών

### ISSUE THREAD

**Issue by Chrz95** [slp-ntua/patrec-labs#141]
Καλησπέρα

Τι τιμές μετρικών αναμένουμε από το LSTM ; Για παράδειγμα, σε εμένα το accuracy είναι πολύ χαμηλό (26~35%), στις διάφορες περιπτώσεις. Είναι αναμενόμενο αυτό ή αναμένουμε εξαιρετική απόδοση, όπως είχαμε στο προηγούμενο εργαστήριο ; 

Ευχαριστώ πολυ

**Comment by georgepar** [comment]
Μέρος αυτού του εργαστηρίου είναι να προσομοιώσουμε ένα πιο ρεαλιστικό σενάριο όπου:

1. Δε θα έχετε να λύσετε κάποιο τρίβιαλ πρόβλημα 
2. Δε θα έχετε το ground truth performance από εμάς, οπότε θα πρέπει να είστε confident ότι έχετε χτίσει τα μοντέλα σας σωστά.

Αν ακολουθήσετε τις μεθόδους debugging και evaluation των μοντέλων που σας έχουμε προτείνει δε θα έχετε πρόβλημα.
