### ISSUE TITLE
Προθεσμία Υποβολής Προπαρασκευής

### ISSUE THREAD

**Issue by johnliak** [slp-ntua/patrec-labs#142]
Καλησπέρα, εφόσον θέλετε η προπαρασκευή να ολοκληρωθεί πριν το εργαστήριο της 17/1, μέχρι πότε επιτρέπεται να υποβάλουμε; Θα υπάρχει κάποιο penalty αν καθυστερήσουμε την υποβολή;

**Comment by georgepar** [comment]
Η άσκηση θα εξεταστεί στο εργαστήριο και θα υπάρχει βαθμολογικό πέναλτυ αν δεν την δούμε εκει.
