### ISSUE TITLE
Lab3: Step 7

### ISSUE THREAD

**Issue by mpektkd** [slp-ntua/patrec-labs#146]
Στο βημα 7 θελετε να εκπαιδευσουμε ενα CNN για καθε dataset? Οπως στο βημα 5? Δλδ για mel, chroma, fused για beat και non-beat?

**Comment by georgepar** [comment]
Δες τις απαντήσεις εδώ https://github.com/slp-ntua/patrec-labs/issues/145

**Comment by mpektkd** [comment]
Ευχαριστω πολυ
