### ISSUE TITLE
Lab 3: Step 10

### ISSUE THREAD

**Issue by mpektkd** [slp-ntua/patrec-labs#147]
Η συναρτηση κοστους που καλουμαστε να υλοποιησουμε, ειναι απλα το αθροισμα L1Loss() για καθε task και ίσως με καποια βαρη?

**Comment by efthymisgeo** [comment]
Ναι αυτό ακριβώς

**Comment by mpektkd** [comment]
Ωραια, ευχαριστω πολυ.

**Comment by mpektkd** [comment]
Επισης, η εξοδος του νευρωνικου στο multitask θα πρεπει να ειναι ενα διανυσμα 1X3?

**Comment by efthymisgeo** [comment]
Όχι. Βάζουμε ένα regression head για κάθε task. Π.χ ένα nn.LInear(*,1) η κάτι πιο σύνθετο

**Comment by mpektkd** [comment]
Οκ, νομιζω καταλαβα.

**Comment by mpektkd** [comment]
Θελετε να πειραματιστουμε και με LSTM και με CNN ή με το καλυτρερο με βαση τα προηγουμενα βηματα?

**Comment by efthymisgeo** [comment]
Το CNN θα πρέπει να πάει καλύτερα. Αλλά μην φάτε πολύ ζωή στο tuning δεν θα βαθμολογηθεί η απόδοση του δικτύου

**Comment by mpektkd** [comment]
Ωραια, ευχαριστω

**Comment by mpektkd** [comment]
Στα regression tasks οπου θελουμε μονο θετικες τιμες σκεφτηκα να βαλω ενα functional  μετα το τελευταιο linear layer. Δοκιμασα Softmax και Sigmoid. Αλλα επαιρνα συνεχως τιμες 1 και 0.5 αντιστοιχα. Δεν μπορω να καταλαβω γτ γινεται αυτο. Ειναι λαθος η σκεψη μου? Ο στοχος μου ηταν θετικες τιμες μεταξυ [0, 1]. Υπαρχει αλλος τροπος να το κανω αυτο?

Συγκεκριμενα στο convolutional layer μετα το conv layer εχω τα εξης:

1. Linear + Relu
2. Linear
3. Sigmoid/Softmax

Ενω στο LSTM απλα κανω apply Softmax/Sigmoid στην τελικη εξοδο
