### ISSUE TITLE
Lab 3 : Step 8

### ISSUE THREAD

**Issue by mpektkd** [slp-ntua/patrec-labs#148]
Εχω το εξης προβλημα με το LSTM και με το CNN. Κατα την εκπαιδευση του το loss πεφτει ειτε mse ειτε l1, αλλα το spearman corr ειναι απογοητευτικο. Το δικτυο πρακτικα δεν μαθαινει καθως απλα προβλεπει συνεχως τιμες στο 0.5+-Δ, ωστε να ελαχιστοποιει το loss αλλα δεν βελτιωνει το correlation οχι. Πως μπορω να το αντιμετωπισω? Σκεφτηκα να ορισω το spearcorr σαν loss_function? Υπαρχει πιο απλος τροπος? Ενα μιξ το mse και l1 θα βοηθουσε?

**Comment by chrisdim** [comment]
επειδή έχω το ίδιο πρόβλημα, τελικά πως το προσέγγισες;
