### ISSUE TITLE
[Lab 3] Προθεσμία υποβολής

### ISSUE THREAD

**Issue by chrisdim** [slp-ntua/patrec-labs#149]
Καλησπέρα,
Δεδομένου ότι η εξέταση του μαθήματος έχει μετατεθεί για 17/2 και σε συνδυασμό με την παράταση της εξεταστικής λόγω της πρόσφατης κακοκαιρίας, ίσως είναι εύλογο η προθεσμία του 3ου εργαστηρίου να μετατεθεί επίσης (χωρίς penalty) στο τέλος της εξεταστικής περιόδου. Γνωρίζω ότι έχει ήδη δοθεί κάποια παράταση, αλλά ήδη σε πολλά μαθήματα έχουν μεταφερθεί προθεσμίες εξαμηνιαίων και εργαστηρίων στο τέλος του Φλεβάρη, ώστε να μπορούμε να διαβάσουμε για την εξεταστική. Μια τέτοια απόφαση για το 3ο lab θα μας διευκόλυνε αφάνταστα πολύ.
Ευχαριστώ εκ των προτέρων.

**Comment by DimLiak** [comment]
Και εγώ συμφωνώ με την παραπάνω πρόταση! Πιστεύω μια παράταση θα ήταν αρκετά βολική, δεδομένου ότι βρισκόμαστε εν μέσω εξεταστικής!

**Comment by chpipis** [comment]
Καλημέρα, ήθελα να ρωτήσω μια διευκρίνιση για την ημερομηνία παράδοσης του 3ου lab.

Επειδή στο Helios έχει deadline στις 28/2 ώρα 00:00 (που σημαίνει ότι επιτρέπεται παράδοση μέχρι **και** 27/2) τι ισχύει τελικά; Αυτή η ημερομηνία είναι χωρίς penalty?

Αν όχι, ποια είναι η τελευταία ημέρα στην οποία μπορούμε να υποβάλλουμε και να μην έχουμε penalty?

Ευχαριστώ!

**Comment by smaragben** [comment]
χωρίς πέναλτυ ισχύει 28/02?

**Comment by georgepar** [comment]
Ισχύει η ημερομηνία και η ώρα στο helios.

**Comment by smaragben** [comment]
στο helios υπαρχει ανακοινωση που λεει οτι τελικη προθεσμια ειναι 21/02 χωρις πεναλτυ οποτε ειναι διφορουμενα τα πραγματα

**Comment by georgepar** [comment]
Η ημερομηνία που λέει στην ενότητα "Εργασίες"
