### ISSUE TITLE
Θέματα overflow/underflow

### ISSUE THREAD

**Issue by michaelbzms** [slp-ntua/patrec-labs#15]
Προσπαθώντας να υλοποιήσουμε τον custom Bayes πολλές πιθανότητες (πχ P(X=x_i | Y=y)) βγαίνουν πολύ μικρές / μεγάλες και προκύπτουν θέματα underflow στις τελικές πιθανότητες. Ο στανταρ τρόπος να το αντιμετωπίσουμε αυτό είναι να κάνουμε το argmax σε log space, έτσι; Δηλαδή να υπολογίσουμε το argmax{ log P(Y | X) } = argmax{ sum( log P(X=x_i | Y=y) ) + P(Y=y) }.

**Comment by georgepar** [comment]
Σωστά. Αυτό είναι κλασικό τρικ για να αντιμετωπίζονται θέματα αριθμητικής ευστάθειας.
