### ISSUE TITLE
Παράδοση εργαστηρίου 3

### ISSUE THREAD

**Issue by tommyshelby4** [slp-ntua/patrec-labs#151]
Υπάρχει πρόβλημα αν στείλουμε notebook? Είναι τόσα πολλά που αν τα κάνουμε σε ένα ή δύο .py αρχεία ο κώδικας θα είναι σκέτο χάος

**Comment by georgepar** [comment]
μπορείτε να ακολουθήσετε τη δομή που σας προτείνουμε εδώ https://github.com/slp-ntua/patrec-labs/tree/main/lab3
