### ISSUE TITLE
Υποβολές Kaggle και παράδοση αναφοράς.

### ISSUE THREAD

**Issue by timtsapras23** [slp-ntua/patrec-labs#152]
Καλησπέρα, για να σχολιάσουμε τα αποτελέσματά μας σε σχέση με αυτά του Kaggle competition θα πρέπει να περιμένουμε και τα αποτελέσματα για το 30% και μετά να υποβάλλουμε την αναφορά μας ή σχολιάζουμε τα 70% και τα 30% θα τα δούμε μετά το πέρας του εργαστηρίου;

**Comment by georgepar** [comment]
Τα 30% θα τα δειτε μετα
