### ISSUE TITLE
Απορία Βήματος 8, Προπαρασκευής 1ης Εργαστηριακής άσκησης.

### ISSUE THREAD

**Issue by ibatsis** [slp-ntua/patrec-labs#154]
Χαίρετε.

Θα μπορούσατε να μου εξηγήσετε τί ακριβώς πρέπει να κάνουμε στο Βήμα 8 της Προπαρασκευής της πρώτης Εργαστηριακής Άσκησης. Δηλαδή πώς θα σχεδιάσουμε το ψηφίο "0" χρησιμοποιώντας τις τιμές της διασποράς του βήματος 6; Θα πρέπει να δημιουργήσουμε έναν πίνακα οι τιμές του οποίου (δηλαδή κάθε pixel) θα είναι η μέση τιμή του βήματος 6, + ή - την τιμή της διασποράς του βήματος 6; Σας ευχαριστώ.

Μπατσής Ιωάννης

**Comment by georgepar** [comment]
Το πρώτο

**Comment by ibatsis** [comment]
Εντάξει, ευχαριστώ.
