### ISSUE TITLE
1η Εργαστηριακή Άσκηση (Step 14)

### ISSUE THREAD

**Issue by ibatsis** [slp-ntua/patrec-labs#159]
Χαίρετε.

Θα ήθελα να ρωτήσω, με βάση το αρχείο lib.py, γιατί για τον υπολογισμό των apriori πιθανοτήτων των κλάσεων δίνονται ώς ορίσματα τόσο τα labels (διάσταση (nsamples)) όσο και τα train data (διάσταση (nsamples x nfeatures)); Το σύνολο των label και το πλήθος του κάθε επιμέρους label δέν επαρκεί για τον προσδιορισμό της apriori πιθανοτήτας κάθε κλάσης; Ευχαριστώ.

Μπατσής Ιωάννης

**Comment by georgepar** [comment]
Ναι τα stubs των συναρτήσεων ειναι από ενδεικτική υλοποίηση. Μπορείτε να κάνετε όπως το πιστεύετε
