### ISSUE TITLE
1η Σειρα Ασκησεων

### ISSUE THREAD

**Issue by iliazzzz** [slp-ntua/patrec-labs#160]
Καλησπέρα σας,

θα ήθελα να ρωτήσω αν υπάρχει σύστημα ποινής και στις σειρές ασκήσεων, γιατί την Πέμπτη ειπώθηκε κάτι τέτοιο από τον κ.Ποταμιάνο (δεν είμαι σίγουρος, για αυτό και ρωτάω). Αν ναι, μέχρι πότε πρέπει να υποβάλλουμε ώστε να μην υπάρχει ποινη;

Ευχαριστώ εκ των προτέρων

**Comment by efthymisgeo** [comment]
H επίσημη είναι 23/11 και με το penalty 30/11

**Comment by iliazzzz** [comment]
> H επίσημη είναι 23/11 και με το penalty 30/11

Ευχαριστώ για την ενημέρωση!!!

**Comment by Georgia256** [comment]
To σύστημα με ποινές ισχύει και για το εργαστήριο; σε περίπτωση που καθυστερήσουμε μία μέρα την υποβολή?

**Comment by georgepar** [comment]
Γενικός κανόνας για όλα τα εργαστήρια και ασκήσεις εκτός αν πούμε κάτι άλλο explicitly 

Προθεσμία στο helios: no penalty
Προθεσμία στο helios + 1 βδομαδα: penalty

**Comment by MundasMahtan** [comment]
Στην 3η άσκηση ,με τον ΕΜ στο GMM , πόσες φορές χρειάζεται να τρέξουμε τον αλγόριθμο και οι αρχικές τιμές που υποθέτουμε για τα μi, σi, pi, i=1,2 είναι τυχαίες;

**Comment by SnifflePiffle** [comment]
Καλησπέρα, θα ήθελα να κάνω δύο ερωτήσεις:
1) Στην άσκηση 1.3 υποθέτουμε τυχαίες αρχικές τιμές για μέσες τιμές και διασπορές και priors ή παίρνουμε αυτές των αρχικών γκαουσιανών?
2) Στην άσκηση 1.5 για το α) ερώτημα, να θεωρήσουμε ότι ο Α είναι συμμετρικός πίνακας?

**Comment by phantom-duck** [comment]
Καλησπέρα, θα ήθελα μερικές διευκρινίσεις σχετικά με την πρώτη σειρά:
1. Στην άσκηση 1.3, υπάρχει κάποιος λόγος που μας ζητείται να παράξουμε εναλλάξ 2 σημεία από την μία κατανομή και 1 από την άλλη; Ποια η διαφορά με το να παράξουμε απλώς 10 από τη μια και 5 από την άλλη, τι σημασία έχει η σειρά;
2. Στο ερώτημα 1.4.e, τι μας ζητείται ακριβώς; Να βρούμε την σημειακή εκτίμηση Bayes για την θ, δηλαδή την MAP, και μετά να την αντικαταστήσουμε στο P(x|D), αντί για ολοκλήρωση, και να δούμε τι βγαίνει; Να αντικαταστήσουμε μια σταθερή τιμή για το θ στην P(x|θ) και να εξισώσουμε αυτό με το P(x|D) που υπολογίσαμε, με το σκεπτικό ότι θέλω μία εκτίμηση της θ που να μου δίνει από μόνη της την πληροφορία που μου δίνει ολόκληρο το D; Βασικά, δυσκολεύομαι πολύ να καταλάβω το ζητούμενο, γιατί από κάποιες οπτικές γωνίες μου φαίνεται σαν η σύνταξη της εκφώνησης, που λέει "Αν Α, τότε ποια είναι η Β;", τα Α και Β να είναι τελείως ανεξάρτητα μεταξύ τους, σαν τα αστειάκια με το "Αν πετάει ένα αεροπλάνο αυτή τη στιγμή από πάνω μας, υπολογίστε την μάζα της Γης". Ντάξει, αστειεύομαι, απλώς προσπαθώ να καταδείξω πώς το βλέπω. Ίσως κάτι να μην έχω καταλάβει, αλλά τι σχέση έχει η αντικατάσταση αυτή με την εκτίμηση Bayes; Αν, βέβαια, εννοούμε την εκτίμηση Bayes όπως την έχουμε ορίσει στο μάθημα και είναι κάτι στάνταρ, δηλαδή η εκ των υστέρων κατανομή της παραμέτρου δεδομένων των δεδομένων P(θ|D). Που δεν είναι και σημειακή, κιόλας, που συμβάλλει και αυτό στο ότι δυσκολεύομαι να καταλάβω την εκφώνηση.

Σε κάθε περίπτωση, ευχαριστώ για την υπομονή.
