### ISSUE TITLE
1η Σειρά Αναλυτικών Ασκήσεων.

### ISSUE THREAD

**Issue by ibatsis** [slp-ntua/patrec-labs#162]
Χαίρεται.

Στην άσκηση 1.3, μπορούμε να χρησιμοποιήσουμε τους τύπους απο το βιβλίο των Θεοδώρίδη και  Κουτρουμπά για τον υπολογισμό των νέων τιμών των παραμέτρων των Gaussian κατανομών ή πρέπει να τους αποδείξουμε πρώτα;

Επίσης θα ήθελα να ρωτήσω αναφορικά με την ημερομηνία παράδοσης, γιατί προβληματίστικα με κάποια προηγούμενα issues που διάβασα. Αρχικά ήταν για τις 23/11. Μετά είδα πως έγινε 30/11. Σε μιά απάντηση διάβασα οτι παράδοση στην ημερομηνία του Helios δέν επιφέρει ποινή, ενώ παράδοση με βάση το Helios και μία εβδομάδα επιφέρει ποινή. Τί ισχύει για αυτήν την περίπτωση; Πρέπει να παραδόσουμε κανονικά στις 23/11 με ποινή στις 30/11 ή κανονικά στις 30/11 με ποινή στις 7/12. Σας ευχαριστώ.

Μπατσής Ιωάννης

**Comment by efthymisgeo** [comment]
Θα πρέπει να τους εξάγεται με βάση τον EM όπως γράφει η εκφώνηση. Ως προς την 1η σειρά ασκήσεων ισχύει η [απάντησή μου](https://github.com/slp-ntua/patrec-labs/issues/160#issuecomment-1313870845)
