### ISSUE TITLE
2o Lab

### ISSUE THREAD

**Issue by Stelios-K** [slp-ntua/patrec-labs#164]
Στο βήμα 2 πρέπει υποχρεωτικά να παίρνουμε τα δεδομένα σε λίστες ή μπορούμε να τα έχουμε και σε np.ndarrays;

**Comment by georgepar** [comment]
Τα δεδομένα έχουν διαφορετικο μηκος οπότε οι λίστες είναι πιο απλές.

Γενικότερα δεν περιορίζουμε τον τρόπο υλοποίησης οπότε αν μπορείτε να το κάνετε σωστά με numpy arrays εγώ δεν έχω προβλημα

**Comment by Stelios-K** [comment]
Σωστά δεν το σκέφτηκα ότι έχουν διαφορετική διάσταση.

Και κάτι ακόμα. Στο βήμα 5 πρέπει να πάρουμε μέση τιμή και διασπορά και για τα deltas πέρα από τα MFCC; Και το scatter plot θα έχει ας πούμε μέση τιμή και διασπρά για τα δύο πρώτα MFCC;

**Comment by georgepar** [comment]
> πρέπει να πάρουμε μέση τιμή και διασπορά και για τα deltas

Ναι

>  Και το scatter plot θα έχει ας πούμε μέση τιμή και διασπρά για τα δύο πρώτα MFCC

Ναι

**Comment by ibatsis** [comment]
Καλησπέρα.

Για το Βήμα 5 στη διαδικασία concatenate πρέπει για κάθε ψηφίο να δημιουργήσουμε τρείς πίνακες (13 x (όσο βγεί σε κάθε ψηφίο)), όπου ο πρώτος θα περιέχει τα όλα τα mfcc, ο δεύτερος όλα τα delta και ο τρίτος όλα τα delta2 που αναφέρονται στο κάθε ψηφίο;

Μπατσής Ιωάννης

**Comment by georgepar** [comment]
Καλύτερα concat 39xn

**Comment by georgepar** [comment]
μπορείτε να δοκιμάσετε και τα δύο και να δείτε τι προσφέρουν τα delta / delta2
