### ISSUE TITLE
pomegranate.

### ISSUE THREAD

**Issue by Panoskininis** [slp-ntua/patrec-labs#168]
Καλησπέρα σας,

Όσον αφορά την χρήση της βιβλιοθήκης pomegranate για το βήμα 10, είναι υποχρεωτική; Επειδή προκύπτουν ορισμένα trust issues, αν κρίνουμε πως μια άλλη βιβλιοθήκη μας συμφέρει περισσότερο μπορούμε να την χρησιμοποιήσουμε ελεύθερα;

Ευχαριστώ εκ των προτέρων.

**Comment by georgepar** [comment]
Τι προτείνετε; hmmlearn?

**Comment by Panoskininis** [comment]
Ναι, ακριβώς.

**Comment by georgepar** [comment]
Μπορείτε να το δοκιμάσετε. Εμείς όταν το είχαμε δοκιμάσει ειχε και αυτή θέματα.
