### ISSUE TITLE
Υλικό από παρουσίαση Lab 2

### ISSUE THREAD

**Issue by phantom-duck** [slp-ntua/patrec-labs#171]
Καλησπέρα.

Αν θυμάμαι καλά, είχατε αναφέρει ότι θα ανεβάσετε το υλικό από το οποίο μας κάνατε την παρουσίαση του εργαστηρίου. Μέχρι στιγμής, όμως, εγώ τουλάχιστον δεν το βλέπω πουθενά. Μπορείτε να μου πείτε που είναι ανεβασμένο, ή αν δεν είναι να το ανεβάσετε;

**Comment by georgepar** [comment]
Τα slides που έδειξα είναι ήδη ανεβασμένα στη σελίδα του μαθήματος, στην ενότητα "Υλικό Εργαστηρίων" (https://helios.ntua.gr/mod/url/view.php?id=5127)
