### ISSUE TITLE
Lab 2.

### ISSUE THREAD

**Issue by ibatsis** [slp-ntua/patrec-labs#172]
Χαίρετε.

Χρησιμοποιώ Google Colab και όταν τρέχω τον κώδικα για την υλοποίηση GMM - HMM βγαίνει το σφάλμα:

Your session crashed after using all available RAM. If you are interested in access to high-RAM runtimes, you may want to check out [Colab Pro](https://colab.research.google.com/signup/pricing?utm_source=dialog&utm_medium=link&utm_campaign=oom).

Υπάρχει περίπτωση να οφείλεται σε λάθος στον κώδικά μου; Σας ευχαριστώ.

**Comment by georgepar** [comment]
Έχουμε ελέγξει τα εργαστήρια για την κατανάλωση σε πόρους ώστε να τρέχουν σε colab / laptop. 

Υποθέτω ότι το πρόβλημα είναι ότι είτε βάζετε μεγάλα μοντέλα, είτε πρόβλημα στο format των δεδομένων
