### ISSUE TITLE
pack_padded_sequence

### ISSUE THREAD

**Issue by TheodoreBartsokas** [slp-ntua/patrec-labs#173]
Καλησπέρα,

Αναφορικά με το τελευταίο υποερώτημα του τελευταίου ερωτήματος, θέλετε να εκτελέσουμε δύο φορές τη διαδικάσια εκπαίδευσης, μια φορά με δεδομένα τα οποία έχουν γίνει εκ των προτέρων padded μέσω των συναρτήσεων της FrameLevelDataset, και μία φορά με δεδομένα στα οποία εφαρμόζεται on the fly padding, με τη χρήση της pack_padded_sequence ή αυτό που ζητάτε είναι κάτι άλλο;

Ευχαριστώ εκ των προτέρων.

**Comment by georgepar** [comment]
Ναι αυτό είναι. Θα πρέπει να συγκρίνετε ως προς την ταχύτητα εκπαίδευσης.
Πρέπει να προσέξετε για σωστή υλοποίηση ότι σε καμία από τις δυο περιπτώσεις δεν πρέπει το padding να επηρρεάζει την ποιότητα του μοντέλου. Το padding εν γενει επηρρεάζει μόνο την ταχύτητα εκπαίδευσης στα RNN.
