### ISSUE TITLE
Early Stopping, Checkpoints

### ISSUE THREAD

**Issue by TheodoreBartsokas** [slp-ntua/patrec-labs#174]
Μπορούμε να χρησιμοποιήσουμε τις έτοιμες υλοποιήσεις των βιβλιοθηκών για αυτές τις δύο λειτουργίες ή πρέπει να τις υλοποιήσουμε εξαρχής;

**Comment by georgepar** [comment]
Εννοείτε pytorch lightning? Γιατί σε Pytorch δεν υπάρχει κάτι έτοιμο διαθέσιμο.

Αν ναι, τότε προτιμούμε εξ αρχής υλοποίηση (να μη βασιστείτε σε ένα τόσο high-level framework).
