### ISSUE TITLE
Απορίες για 2η Σειρά Ασκήσεων

### ISSUE THREAD

**Issue by NickSpanos55** [slp-ntua/patrec-labs#176]
Καλησπέρα σας. Έχω δύο απορίες για την σειρά ασκήσεων:
1. Στην άσκηση 2.1 στο ερώτημα 2 το αποτέλεσμα του expression το υπολογίζω ως 0. Κάνω κάποιο λάθος ή παίζει ρόλο η δεύτερη παράγωγος της activation function?
2.  Στην άσκηση 2.2 δεν χρειάζεται να γνωρίζουμε την Loss Function για να υπολογίσουμε κάποιες τιμές για το chain rule? 
Σας ευχαριστώ και απολογούμε αν οι ερωτήσεις είναι χαζές.

**Comment by georgepar** [comment]
1. Ναι κάνετε κάποιο λάθος (πιθανώς τραβάτε ένα - έξω από το σ? το οποίο είναι λάθος γιατί η σ εδώ δεν είναι γραμμική). Το σ''(0)  μπορείτε να το θεωρήσετε μια σταθερά και δεν παίζει ρόλο σε αυτό το ερώτημα.
2. Όχι. Συγκεκριμένα "The final expression should be in terms of Lt". Το οποίο σημαίνει ότι δε χρειάζεται να γνωρίζετε τη συνάρτηση κόστους.

PS: Δεν υπάρχουν χαζές ερωτήσεις.

**Comment by NickSpanos55** [comment]
Οκ σας ευχαριστώ πολύ. Επίσης, μήπως στο 3ο ερώτημα της άσκησης 2.1 είναι λ->1?

**Comment by georgepar** [comment]
Οχι

**Comment by gkrinias** [comment]
Καλησπέρα,

Στην άσκηση 2.1 μήπως είναι μ = (4 λ^2 σ"(0))^-1 αντι για (4 λ σ"(0))^-1 ;

**Comment by georgepar** [comment]
ναι έχετε δίκιο. Θα ανεβάσω διορθωση

**Comment by Panoskininis** [comment]
Καλησπέρα σας και χρόνια πολλά,

Θα ήθελα μια ερώτηση όσον αφορά το 3ο ερώτημα της άσκησης 2.1. Δεν γίνεται το όρισμα της συνάρτησης tilde(f(x)) να είναι βαθμωτό αφού για να επιτευχθεί ο πολλαπλασιασμός με τον πίνακα W1, θα πρέπει αν έχει 2 γραμμές. Οπότε, να θεωρήσουμε πως το x στην tilde(f(x)) είναι διανυσματικό; Αν ναι, τότε η multiplication function απλά ορίζεται ως το γινόμενο των στοιχείων του διανύσματος; Ρωτάω επειδή στο ερώτημα 2 τα x1 και x2 είναι scalar.

Ευχαριστώ εκ των προτέρων.

**Comment by georgepar** [comment]
x = [x1, x2]

**Comment by ibatsis** [comment]
Χαίρετε.

Στην άσκηση 2.1, θεωρούμε ώς activation function την σ(x) = x για όλα τα ερωτήματα, σωστά; Σας ευχαριστώ. Καλό απόγευμα και καλή χρονιά.

**Comment by georgepar** [comment]
Όχι χρησιμοποιείτε γραμμικό activation μόνο στο πρώτο υποερωτημα.

Στα υπόλοιπα είναι μια αυθαίρετη μη γραμμικότητα (με μη μηδενική δεύτερη παραγωγό στο 0)

**Comment by ibatsis** [comment]
Μία ακόμη ερώτηση σχετικά με την ίδια άσκηση. Η μεταβλητή x είναι στις 2 - διαστάσεις, [x1 x2]. Όταν λέμε δεύτερη παράγωγος της σ( ) στο 0, εννοούμε για x = [0 0]; Επίσης όταν λέμε δεύτερη παράγωγος της σ( ), εννοούμε όλες τις παραγώγους του Εσσιανού πίνακα ( dσ( )/(dx1dx1) , dσ( )/(dx1dx2) , dσ( )/(dx2dx1) , dσ( )/(dx2dx2)) ;

**Comment by georgepar** [comment]
Η σ εφαρμόζεται element-wise, όπως πχ η sigmoid ή η relu. Άρα η σ είναι μια scalar συνάρτηση από το R->R

**Comment by nikgalanop** [comment]
Καλησπέρα σας και χρόνια πολλά!

Θα ήθελα να σας ρωτήσω για την άσκηση 2. Μας ζητείται να υπολογίσουμε τη gradient του L_t ως προς κάποιες μεταβλητές. Αν καταλαβαίνω σωστά το L_t είναι η μετρική του λάθους που μας ενδιαφέρει, μόνο για την έξοδο της στιγμής t. (Σύμφωνα τουλάχιστον με το notation που διαβάζω στο κεφ. 10 του Goodfellow.)
 
> 2. Όχι. Συγκεκριμένα "The final expression should be in terms of Lt". Το οποίο σημαίνει ότι δε χρειάζεται να γνωρίζετε τη συνάρτηση κόστους.

Αναφέρετε πως πρέπει η τελική έκφραση της μερικής παραγώγου να είναι εκφρασμένη ως προς κάποιες μεταβλητές μεταξύ των οποίων και το L_t. Ωστόσο, δεν γνωρίζουμε τίποτα για καμία μερική παράγωγο του L_t. Δεν καταλαβαίνω πως, στον κανόνα της αλυσίδας, θα απαλλαχθούμε από τη μερική παράγωγο που θα περιέχει το L_t. 

Σας ευχαριστώ εκ των προτέρων.

**Comment by grilio** [comment]
Καλή χρονιά!
Στην άσκηση 2.1 στο ερώτημα 2 μήπως ο ορισμός του b είναι b^T = [0 0 0 0] και όχι b = [0 0 0 0];
Ευχαριστώ!

**Comment by georgepar** [comment]
Καλησπέρα και καλή χρονιά,

@nikgalanop Η τελική έκφραση θα περιέχει ένα όρο με τη μερική παράγωγο του L_t, οπότε δε χρειάζεται να ξέρετε κάποια συγκεκριμένη συνάρτηση κόστους. Η έκφραση είναι γενική για όλες τις συναρτήσεις κόστους

@grilio δε θυμάμαι τις διαστάσεις, αλλά αν ταιριάζει το b^T χρησιμοποιήστε αυτό.

**Comment by ilianasilou** [comment]
Καλησπέρα και καλή χρονιά,

Μέχρι πότε πρέπει να παραδώσουμε χωρίς το πέναλτυ;

**Comment by grilio** [comment]
στην άσκηση 2.3 γράφετε y_i ανήκει στο {1,1}, μήπως έχει γίνει κάποιο τυπογραφικό?

**Comment by Kontilenia** [comment]
Καλημέρα και καλή χρονιά.
Υπάρχει περίπτωση να δωθεί κάποια παράταση για την παράδοση της δεύτερης σειράς αναλυτικών ασκήσεων; 
Ευχαριστώ!

**Comment by iliazzzz** [comment]
Καλησπέρα και χρονια πολλά!!!

Στην άσκηση 2.2 για το πρώτο ερώτημα πρέπει να αντικαταστήσουμε την f με π.χ. tanh;

Ευχαριστώ εκ των προτέρων 😄

**Comment by georgepar** [comment]
Όχι θα βγάλετε ενα γενικό τύπο για την f

**Comment by georgepar** [comment]
Σχετικά με παράταση, θα επανέλθω αύριο

**Comment by thAlexx** [comment]
Καλησπέρα και καλή χρονιά!!

Στην άσκηση 2.3, στο ερώτημα 2), μήπως έχει γίνει κάποιο λάθος και έπρεπε να έχουμε -2<K(u,v)<2 (για u!=v);; Γιατί προσωπικά δεν μου βγαίνει με τίποτα το ζητούμενο αν -1<K(u,v)<1.

Ευχαριστώ!!

**Comment by MundasMahtan** [comment]
Καλησπέρα,
Στην άσκηση 2.2 μήπως τo output υπολογίζεται ως o_t=V*h_t και όχι ως o_t=f(V*h_t)?
Ευχαριστώ εκ των προτέρων

**Comment by ShortMaggot** [comment]
Καλησπέρα!

Σχετικά με την παράταση, υπάρχει περίπτωση να δωθει; διότι ο φόρτος είναι μεγάλος.

**Comment by georgepar** [comment]
Θα δωθεί μια βδομάδα παράταση. Θα βγει αύριο σχετική ανακοίνωση

**Comment by phantom-duck** [comment]
Καλησπέρα και καλή χρονιά!

Σε παρόμοιο μήκος κύματος με ερώτηση προηγούμενου συναδέλφου, στην άσκηση 2.2, στα atoms της τελικής έκφρασης δεν συμπεριλαμβάνεται η f. Ωστόσο, από την στιγμή που o_t = f(V h_t), μου φαίνεται ότι θα πρέπει να συμμετέχει στην τελική έκφραση όχι μόνο η f, αλλά και η παράγωγός της, υποχρεωτικά. Δεν καταλαβαίνω γιατί δεν ισχύει αυτό;

**Comment by billsioros** [comment]
> Θα δωθεί μια βδομάδα παράταση. Θα βγει αύριο σχετική ανακοίνωση

Υπάρχει κάποιο νεότερο; Ευχαριστώ!
