### ISSUE TITLE
Βήμα 5, Εργαστηριακή Άσκηση 3

### ISSUE THREAD

**Issue by Panoskininis** [slp-ntua/patrec-labs#177]
Καλησπέρα σας,

Στο βήμα 5 της εργαστηριακής άσκησης 3 μπορούμε να χρησιμοποιήσουμε εκτός από τον αντίστοιχο κώδικα που υλοποιήσαμε στην 2η εργαστηριακή άσκηση αυτόν που μας δίνεται εδώ: https://github.com/slp-ntua/patrec-labs/blob/main/lab3/lstm.py ;

Ευχαριστώ εκ των προτέρων.

**Comment by pxaris** [comment]
Ναι φυσικά.
