### ISSUE TITLE
Υποβολή Προπαρασκευής 3ου Εργαστηρίου

### ISSUE THREAD

**Issue by nickhaidos** [slp-ntua/patrec-labs#178]
Καλησπέρα σας,

Σχετικά με τα παραδοτέα για το 3ο εργαστήριο, θέλετε στο zip να συμπεριλάβουμε το .ipynb όπως βγαίνει από το Kaggle, ή να το κάνουμε .py όπως τα προηγούμενα εργαστήρια?

Ευχαριστώ

**Comment by pxaris** [comment]
Καλησπέρα,
Ό,τι και στα προηγούμενα εργαστήρια. Σημειώστε ότι η αναφορά σας (αρχείο pdf) θα πρέπει να παραδοθεί, αφού λάβει χώρα το εργαστήριο (στις 9/1), για το σύνολο της εργαστηριακής άσκησης. Καλές γιορτές!
