### ISSUE TITLE
Συμπληρωματικό Εργαστήριο πάνω στο Pytorch

### ISSUE THREAD

**Issue by Annepkn** [slp-ntua/patrec-labs#179]
Καλημέρα και χρόνια πολλά!

Με αφορμή και το issue #170, επαναφέρω την ανάγκη για ένα φροντιστηριακό μάθημα πάνω στο Pytorch. Δεν προλάβαμε να δούμε PyTorch καθόλου στο φροντιστήριο της Python ωστόσο το lab3 είναι η δεύτερη εργαστηριακή άσκηση που καλούμαστε να το χρησιμοποιήσουμε. Υπάρχουν αρκετές απορίες σε προαπαιτούμενες γνώσεις που η πλειοψηφία δεν έχει,  οπότε ένα μάθημα πάνω σε αυτό θα ήταν αρκετό βοηθητικό.

**Comment by pxaris** [comment]
Επίσης χρόνια πολλά!

Στο εργαστήριο που θα γίνει τη Δευτέρα θα εστιάσουμε στη χρήση του pytorch, στο πλαίσιο της 3ης εργαστηριακής άσκησης. Εκεί θα μας δοθεί η δυνατότητα να λύσουμε απορίες ενώ εργαζόμαστε "hands-on" για την άσκηση.
