### ISSUE TITLE
[Lab1] __init__ Βήμα 12 και Βήμα 15

### ISSUE THREAD

**Issue by odytokoumbo** [slp-ntua/patrec-labs#18]
Καλημέρα,
Ήθελα να ρωτήσω αν μπορούμε να προσθέσουμε πράγματα στην __init__ ή πρέπει να την αφήσουμε ως έχει. Για παράδειγμα στο βήμα 12 πώς θα ξέρουμε στο predict τον αριθμό των κλάσεων αν δεν υπάρχει self.classes_? (δίνουμε σαν ορισμα μόνο το Χ)
Επίσης στο βήμα 15 θα με βόλευε να έχω self.priors_ και άλλες μεταβλητές private.

**Comment by georgepar** [comment]
Μην αλλάξετε τα ορίσματα καμίας συνάρτησης / μεθόδου.

Κατά τα άλλα μπορείτε να προσθέσετε private μεταβλητές, αρκεί να χρησιμοποιούνται μόνο μέσα στην κλάση.
