### ISSUE TITLE
Απορία για Spearman Correlation LSTM

### ISSUE THREAD

**Issue by NickSpanos55** [slp-ntua/patrec-labs#182]
Καλησπέρα σας. Θα μπορούσατε να μας διευκρινίσετε ποιες είναι οι αναμενόμενες τιμές για το Spearman Correlation των LSTM μοντέλων? Εμείς γενικά δεν παρατηρούμε καλά αποτελέσματα, ειδικότερα είναι στα αρνητικά, και δεν γνωρίζουμε αν είναι σωστό ή όχι. Σας ευχαριστούμε πολύ.

**Comment by pxaris** [comment]
Κάτι ανάμεσα σε 0.1 κα 0.4 είναι αναμενόμενο για τις 3 διαστάσεις. Τρέξτε ξανά τα μοντέλα σας. Αν δείτε να αλλάζουν αρκετά τα αποτελέσματα, κάποια υπερ-παράμετρος θέλει καλύτερο κούρδισμα (δοκιμάστε να αλλάξετε το learning rate). Αν έχετε τα ίδια αποτελέσματα, δείτε αναλυτικά τον κώδικα μήπως υπάρχει κάποιο bug.  
Προχωρήστε σε κάθε περίπτωση σε Transfer learning (και Multitask learning στη συνέχεια) όπου θα πάρετε καλύτερα αποτελέσματα.
