### ISSUE TITLE
Αλλαγη ημερομηνιας εξετασης

### ISSUE THREAD

**Issue by narrativebid** [slp-ntua/patrec-labs#184]
Καλησπέρα σας,

Δεδομένου ότι η προθεσμία για το 3ο εργαστήριο τελειώνει στις 23/01 (χωρίς ποινή), υπάρχει περίπτωση η εξέτασή του μαθήματος να μεταφερθεί στην επόμενη εβδομάδα έτσι ώστε να έχουμε περισσότερο χρόνο για να προετοιμαστούμε;  

Ευχαριστώ εκ των προτέρων.

**Comment by yasonkal** [comment]
+1

**Comment by margaritatsarb** [comment]
+1

**Comment by hightechhh** [comment]
+1

**Comment by nic1cj** [comment]
+1

**Comment by getsironis** [comment]
+1

**Comment by deinfrue** [comment]
+1

**Comment by nic1cj** [comment]
https://strawpoll.com/polls/DwyoDEjvJnA

**Comment by nic1cj** [comment]
https://strawpoll.com/polls/DwyoDEjvJnA
