### ISSUE TITLE
Lab 3 - Βήμα 9

### ISSUE THREAD

**Issue by nikgalanop** [slp-ntua/patrec-labs#186]
Καλημέρα σας,

Στο βήμα 9 που καλούμαστε να κάνουμε transfer learning, όταν εκπαιδεύουμε τον regressor, πρέπει να διασφαλίσουμε ότι τα βάρη του backbone είναι non-trainable ή όχι; Το fine tuning αφορά όλο το μοντέλο ή μόνο το γραμμικό επίπεδο μετά το backbone;

**Comment by pxaris** [comment]
Καλημέρα,
Μπορείτε να πειραματιστείτε σε αυτό αν θέλετε. Θα ξεκινούσα, πάντως, αφήνοντας trainable όλο το δίκτυο, αφού αρχικοποιηθεί με τα αποθηκευμένα βάρη. Αλλά και άλλες τακτικές είναι σίγουρα αποδεκτές και σε περίπτωση που στοχεύαμε στη βέλτιστη επίδοση, θα έπρεπε να διερευνηθούν.
