### ISSUE TITLE
Υποβολή Εργασίας

### ISSUE THREAD

**Issue by yasonkal** [slp-ntua/patrec-labs#188]
Καλησπέρα σας,
Δεδομένου ότι το Kaggle δεν κάνει σωστό formatting του κώδικα από notebook σε script (δηλ. .ipynb -> .py), γίνεται να υποβάλουμε τον τελικό κώδικα σε .ipynb;

**Comment by georgepar** [comment]
όχι. Μπορείτε να κατεβάσετε το notebook τοπικά και να κάνετε export
