### ISSUE TITLE
παραταση 3η εργαστηριακής

### ISSUE THREAD

**Issue by grilio** [slp-ntua/patrec-labs#189]
Καλησπέρα σας,
δεδομένης της ακύρωσης και μεταφοράς μαθημάτων στις 20 και 21 Φεβρουαρίου, υπάρχει περίπτωση να δοθεί παράταση και στην εργαστηριακή άσκηση;
Ευχαριστώ

**Comment by pxaris** [comment]
Καλησπέρα, όχι, ισχύει ότι _"μπορείτε να παραδώσετε με πλήρη βαθμό μέχρι τις 17 Φεβρουαρίου, και με πέναλτυ 10% επί του βαθμού μέχρι τις 24 Φεβρουαρίου"_, όπως αναφέρεται [εδώ](https://helios.ntua.gr/mod/assign/view.php?id=30574).
