### ISSUE TITLE
Προπαρασκευή 1ου Εργαστηρίου - Απορία

### ISSUE THREAD

**Issue by Xron7** [slp-ntua/patrec-labs#190]
Καλησπέρα σας,

Στο βήμα 5 αναγράφεται ο υπολογισμός μέσης τιμής και τυπικής απόκλισης, το διάγραμμα διασποράς θα γίνει με αυτά τα δύο υπολογισμένα χαρακτηριστικά ή με τις 2 πρώτες διαστάσεις του αρχικού διανύσματος (που περιέχει τα 39 χαρακτηριστικά);

Ομοίως για το βήμα 6 μετά το PCA χρειάζεται να κατασκευάσουμε το MEAN-STD διάνυσμα και να τυπώσουμε αυτό σε διάγραμμα διασποράς ή να τυπώσουμε τις 2 διαστάσεις που προκύπτουν;

Σας ευχαριστώ!

**Comment by georgepar** [comment]
Στην αρχή έχετε πινακες (Timesteps x 39) για κάθε εκφώνηση. Θα πάρετε το μέσο όρο ως προς τα timesteps  για να καταλήξετε σε διανύσματα διάστασης 39 και μετά τις 2 πρώτες διαστάσεις αυτών των διανυσμάτων. 

Το ίδιο πράγμα, απλά αντί να πάρετε τις 2 πρώτες διαστάσεις θα εκπαιδεύσετε ένα PCA για να μειώσετε τις διαστάσεις.

**Comment by pGiad** [comment]
Άρα, το τελικό διάνυσμα θα περιέχει μόνο τις μέσες τιμές των timesteps, ή θα πρέπει να προσθέσουμε και την τυπική απόκλιση αυτών;
