### ISSUE TITLE
Απορία για το αρχείο hmm.py

### ISSUE THREAD

**Issue by Xron7** [slp-ntua/patrec-labs#195]
Καλησπέρα στη συνάρτηση:
`def initialize_and_fit_normal_distributions(X, n_states):
    dists = []
    for _ in range(n_states):
        # TODO: YOUR CODE HERE
        d = ...  # Fit a normal distribution on X
        dists.append(d)
    return dists`

υπάρχει ενδεχόμενο να εννοούμε n_mixtures και όχι n_states; Το υποπτεύομαι από τη γραμμή 56:
`distributions = ...  # n_mixtures gaussian distributions`

**Comment by lathanasiadis** [comment]
(με την επιφύλαξη ότι μπορεί να κάνω λάθος)
Αυτή είναι η συνάρτηση που χρησιμοποιείς όταν η μεταβλητή `gmm` είναι False.
Δηλαδή όταν η `gmm` είναι True χρησιμοποιείς GMMs στα HMM με την `initialize_and_fit_gmm_distributions`, αλλιώς χρησιμοποιείς κανονικές κατανομές με την `initialize_and_fit_normal_distributions`

**Comment by Xron7** [comment]
Ok, βγάζει νόημα υποθέτω. Ευχαριστώ!

Επίσης στις δύο αυτές συναρτήσεις πρέπει να γίνει κάποιος διαχωρισμός των δεδομένων με βάση το n_states, ή σε κάθε iteration του for-loop δίνουμε ολόκληρο το X;

**Comment by georgepar** [comment]
Σε όλα τα states δίνετε ολοκληρο το Χ.

Κατά τα άλλα, όπως τα είπε πολύ σωστά ο @lathanasiadis
