### ISSUE TITLE
Βήμα 11

### ISSUE THREAD

**Issue by n-hatz** [slp-ntua/patrec-labs#196]
Καλησπέρα σας, παρατηρούμε όταν εκπαιδεύουμε HMM με **1** state και 1-5 mixtures πετυχαίνουμε τιμές accuracy 0.7-0.9, ενώ όταν αυξάνουμε τον αριθμό των states όλα τα δείγματα ταξινομούνται στην ίδια κλάση, με αποτέλεσμα το accuracy να είναι πάντα 0.1 (φαίνεται ότι κάποιο από τα 10 HMMs βγάζει τη μεγαλύτερη πιθανότητα πάντα).  Γνωρίζετε μήπως που μπορεί να οφείλεται αυτό?

Επίσης, ορισμένες φορές μας συμβαίνει το παρακάτω error κατά την εκπαίδευση των HMMs, αλλά όχι consistently
![image](https://github.com/slp-ntua/patrec-labs/assets/61197261/eb9a5196-06d9-4183-8c41-f92e56ba1572)
Μπορούμε να κάνουμε κάτι για αυτό?

**Comment by n-hatz** [comment]
Οκ όσον αφορά την πρώτη ερώτηση μάλλον είναι τυχαίο, γιατί κάποιες φορές βγαίνουν και φυσιολογικές τιμές accuracy (~0.8-0.95)

**Comment by georgepar** [comment]
Ναι αν γίνει πολύ μεγάλος ο αριθμός των states μπορεί να αποκλίνει. Οπότε αυτό που βλέπετε είναι φυσιολογικό.

Δοκιμάστε διαφορετικούς συνδυασμούς, και αναφέρετε τι παρατηρείτε στην αναφορά.

**Comment by n-hatz** [comment]
Κατανοητό, ευχαριστώ
