### ISSUE TITLE
[Lab 1, Βήμα 19] Error της (sklearn) cross_val_score για constructor (self, *args, **kwargs)

### ISSUE THREAD

**Issue by SergeantChris** [slp-ntua/patrec-labs#33]
Καλώντας την cross_val_score με input μοντέλο το lib.PytorchNNModel() που έφτιαξα σύμφωνα με το layout της κλασης που δώθηκε στο lib (δηλαδή ο constructor να έχει input arguments *args και **kwargs), παίρνω το παρακάτω error:

`scikit-learn estimators should always specify their parameters in the signature of their __init__ (no varargs). <class '__main__.PytorchNNModel'> with constructor (self, *args, **kwargs) doesn't  follow this convention.`

Αλλάζοντας τον constructor σε `__init__(self)` όλα κυλάνε κανονικά (δεν έχω επιλέξει να του δίνω κάποιο εξωτερικό argument).

**Comment by georgepar** [comment]
Οκ θα το λάβουμε υπόψη μας
