### ISSUE TITLE
Ώρα παράδοσης

### ISSUE THREAD

**Issue by vassilispan** [slp-ntua/patrec-labs#36]
Καλησπέρα. Αν παραδώσουμε σήμερα το βράδυ μετά τις 12.00 η υποβολή πιάνεται ως εκπρόθεσμη με penalty ή οχι; Μας έχει μείνει μόνο το bonus ερώτημα που δουλεύουμε, όλα τα άλλα τα έχουμε έτοιμα. Απλώς σε περίπτωση που θεωρηθεί εκπρόθεσμη, θα διακόψουμε το βήμα 19

**Comment by georgepar** [comment]
υποβάλλετε πριν τις 12. Μετα μπορείτε να μας στείλετε το 19 και θα το μετρήσουμε.
