### ISSUE TITLE
Αναλυτική Άσκηση 1.7 (γ)

### ISSUE THREAD

**Issue by BlackPianoCat** [slp-ntua/patrec-labs#38]
Δεν ξέρω εάν εδώ μπορούμε να κάνουμε απορίες και για τις αναλυτικές εργασίες αλλά θα κάνω μια σύντομη ερώτηση.

Στην άσκηση 1.7 στο (γ) λέει:

> (γ) Χρησιμοποιώντας ένα από τα παραπάνω δεδομένα τη φορά, και εφαρμόζοντας τον αλγόριθμο Least Mean Squares (LMS) Υποκεφάλαιο 5.8 του βιβλίου [2]), να υπολογίσετε εκ νέου τους άγνωστους συντελεστές.

Όταν λέτε "θεωρήστε ένα από τα παραπάνω δεδομένα την φορά", τι εννοείται; Θέλετε να θεωρήσουμε έναν από τους δύο συντελεστές που βρήκαμε στο προηγούμενο ερώτημα δεδομένο ως αρχική τιμή και τον άλλο αυθαίρετο; Ή θέλετε να περνάει ένα ένα τα δεδομένα (αυτό δεν καταλαβαίνω πως μπορεί να γίνει αφού απότι βλέπω ο LMS αλγόριθμος δουλεύει με αθροίσματα πάνω σε όλα τα δεδομένα);

_Και μια τελευταία ερώτηση: Όταν λέτε ότι δεν θέλετε προγραμματιστική υλοποίηση, εννοείται ότι είναι προαιρετική; Σας πειράζει δηλαδή εάν αντί για κομπιουτεράκι χρησιμοποιήσουμε την python;_

**Comment by georgepar** [comment]
Η ομάδα των αναλυτικών ασκήσεων χρησιμοποιούν το moodle https://courses.pclab.ece.ntua.gr/mod/forum/view.php?id=293, οπότε καλύτερα να το προωθήσεις εκει.
