### ISSUE TITLE
[Lab 2] Step 11

### ISSUE THREAD

**Issue by pmisiakos** [slp-ntua/patrec-labs#42]
Καλησπέρα,

Στην εκφώνηση αναφέρεται ότι θα γίνει fitting των HMM με Expecation Maximization. 
Πρέπει να το υλοποιήσουμε εμείς αυτό με κάποιον τρόπο; 
Διότι στο documentation της pomegranate αναφέρει ότι το fitting γινεται με έναν από τους παρακάτω τρόπους: 
* ‘baum-welch’
* ‘viterbi’
* ‘labeled’

**Comment by georgepar** [comment]
Θα σου πρότεινα να διαβάσεις λίγο στο bishop για το baum - welch

**Comment by pmisiakos** [comment]
Δεν το πρόσεξα, ευχαριστώ!
