### ISSUE TITLE
Recommended package versions for pomegranate

### ISSUE THREAD

**Issue by georgepar** [slp-ntua/patrec-labs#44]
Από απάντηση περσυνού φοιτητή:

Επειδή και άλλοι ίσως να συνάντησαν το ίδιο πρόβλημα όπου το accuracy έβγαινε πολύ χαμηλό (< 60%) χωρίς να υπάρχει κάποιο σφάλμα στον κώδικα, παραθέτω τις εκδόσεις των πακέτων για Python 3.7.3 για τις οποίες βγαίνει σωστό accuracy (για να μην υπάρχει τυχόν πρόβλημα σε dependencies περιλαμβάνονται και πακέτα που δεν σχετίζονται με το πρόβλημα).

```
gensim==3.8.1
librosa==0.7.1
matplotlib==3.1.0
nltk==3.4.4
numpy==1.16.4
pandas==0.24.2
pomegranate==0.12.0
scikit-image==0.15.0
scikit-learn==0.21.2
scipy==1.3.0
seaborn==0.9.0
torch==1.3.1
torchvision==0.4.2
tqdm==4.32.1
```

**Comment by foivospar** [comment]
Καλησπέρα,

Όταν χρησιμοποιώ τα παραπάνω πακέτα σε ξεχωριστό conda env (για να αποφύγω το γνωστό πρόβλημα με το χαμηλό accuracy), μου προκύπτει νέο σφάλμα, της μορφής :

![Screenshot from 2020-12-12 21-24-16](https://user-images.githubusercontent.com/58859493/101993167-3033fc00-3cc1-11eb-98c9-9045d1f5b214.png)

Για απλή `MultivariateGaussianDistribution` τρέχει κανονικά (με υψηλό accuracy δηλαδή). Στο GMM όμως βγάζει αυτό το error. Δοκίμασα να αλλάξω την παράμετρο `init` της `GeneralMixtureModel.from_samples()` μήπως φταίει ο kmeans++ που χρησιμοποεί για αρχικοποίηση των παραμέτρων της κατανομής, αλλά προκύπτουν νέα σφάλματα. Υπάρχει περίπτωση να φταίνε πάλι τα πακέτα;

**Comment by nikosanto13** [comment]
@foivospar Μας προέκυπτε το ίδιο πρόβλημα και λύθηκε μετατρέποντας το όρισμα X σε float64.

**Comment by foivospar** [comment]
Πράγματι @nikosanto13 , σε ευχαριστώ πολύ !

**Comment by nickzpower** [comment]
@georgepar   Μου έχει προκύψει και μενα και στην συνεργάτιδά μου  παρόμοιο πρόβλημα  .Βέβαια , προσπαθώ να φτιάξω ένα venv που να περιέχει τα παραπάνωω .  Με conda δεν βρίσκει τα μισά πακέτα από αυτά που αναφέρονται παραπάνω . Και με pip υπάρχει παρόμοιο θέμα .Μπορείτε σας παρακαλώ να ανεβάσετε στο site , μια σειρά εντολών για  κατασκευή ενός venv με conda η pip  σύμφωνα με τις νέες ανανεωμένες βιβλιοθήκες ?  Γιατι και εχω και η συνεργάτιδα μου ( και φαντάζομαι και άλλοι συνάδελφοι ) έχουμε φάει αρκετό χρόνο με αυτό χωρίς να βγάλουμε άκρη .

**Comment by BlackPianoCat** [comment]
Λοιπόν εάν θες να φτιάξεις environment στην anaconda, με τα πακέτα που δίνει το κάνεις με `pip install <package-name==version>`, όχι με τον άλλο τρόπο που έχει η anaconda. Και πρέπει επιπλέον να βάλεις και μια βιβλιοθήκη `pip install numba==0.48.0`. Και μην ανησυχείς θα συνεχίσει να σου πετάει errors και να σου κάνει την ζωή δύσκολη. Καλή δύναμη!  :)

**Comment by georgepar** [comment]
To γράφω λιγο αναλυτικά:

```
conda create -n lab2 python=3.6
conda activate lab2
pip install gensim==3.8.1 matplotlib==3.1.0 nltk==3.4.4 numpy==1.16.4 pandas==0.24.2 pomegranate==0.12.0 scikit-image==0.15.0 scikit-learn==0.21.2 scipy==1.3.0 seaborn==0.9.0 torch==1.3.1 torchvision==0.4.2 tqdm==4.32.1
pip install numba==0.48.0 --ignore-installed
pip install librosa==0.7.1
```

**Comment by dimitriskranias** [comment]
Να προσθέσω ότι ίσως χρειάζεται και pip install joblib==0.17.0 διότι σε εμένα και τον συνεργάτη μου που έτρεχε με joblib==1.0.0 (που εγκαθιστόταν λόγω dependency) εμφανιζόταν το εξής error message: 
TypeError: delayed() got an unexpected keyword argument 'check_pickle'

**Comment by tommyshelby4** [comment]
μετα την εγκατασταση των dependencies που εχετε παραθεσει παραπανω το προγραμμα μου σταματησε να τρεχει εντελως
