### ISSUE TITLE
[Lab 2] - Βήματα 4-5

### ISSUE THREAD

**Issue by konskoko** [slp-ntua/patrec-labs#45]
**Βήμα 4:**

Εδώ εννοείτε __2 εκφωνήσεις για καθένα από τα n1, n2__ ή __συνολικά 2 εκφωνήσεις__, μία για κάθε ψηφίο και από διαφορετικό ομιλητή η καθεμία;
> Εξάγετε για 2 εκφωνήσεις των n1 και n2 από 2 διαφορετικούς ομιλητές τα Mel Filterbank Spectral Coefficients (MFSCs)

---

**Βήμα 5:**
> Ενώστε τα mfccs – deltas – delta-deltas και έπειτα για κάθε εκφώνηση δημιουργείστε ένα διάνυσμα παίρνοντας
τη μέση τιμή και την τυπική απόκλιση κάθε χαρακτηριστικού για όλα τα παράθυρα της εκφώνησης.
1. Πώς εννοείτε να ενώσουμε τα mfccs – deltas – delta-deltas? Vertical stack? Άρα να πάρουμε ~~2χ2~~ 2D πίνακα με 39 γραμμές;

2. Αν ισχύει το παραπάνω, τότε η μέση τιμή και τυπική απόκλιση θα μας δώσουν δύο vectors μεγέθους 39. Αυτά θα τα κάνουμε concatenate για να πάρουμε ένα τελικό feature vector μεγέθους 78?

**Comment by georgepar** [comment]
1. απλό concatenation θέλουμε. Άρα τα τελικά features θα έχουν διάσταση 39. το 2χ2 δεν ξέρω τι εννοείς αλλά υποθέτω λέμε το ίδιο.
2. ναι

**Comment by konskoko** [comment]
Ευχαριστώ. Και σχετικά με την ερώτηση για το βήμα 4;

> Εδώ εννοείτε **2 εκφωνήσεις για καθένα από τα n1, n2** (άρα 4 σύνολο) ή **συνολικά 2 εκφωνήσεις**, μία για κάθε ψηφίο και από διαφορετικό ομιλητή η καθεμία;
> > Εξάγετε για 2 εκφωνήσεις των n1 και n2 από 2 διαφορετικούς ομιλητές τα Mel Filterbank Spectral Coefficients (MFSCs)

**Comment by georgepar** [comment]
2 εκφωνήσεις για το καθένα. Θέλουμε να συγκρίνετε τα features για ίδια και για διαφορετικά ψηφία.

**Comment by andretri** [comment]
To correlation που ακριβώς ζητάτε να γίνει στα μητρώα (13 x #Frames)  ή στα (39, ) vectors;

**Comment by georgepar** [comment]
Στα 39

**Comment by kvilouras** [comment]
> Στα 39

η συσχέτιση αφορά το βήμα 4 (MFCCs vs. MFSCs). Από την εκφώνηση καταλαβαίνω ότι πρέπει να προκύψει ένας πίνακας 13x13 για κάθε εκφώνηση ξεχωριστά, έτσι ώστε να δούμε κατά πόσο είναι συσχετισμένοι οι συντελεστές μεταξύ τους. Καταλαβαίνω κάτι λάθος;

**Comment by georgepar** [comment]
είτε 13χ13 αν επιλέξετε τα mfcc χωρίς τις παραγώγους είτε 39χ39 αν βάλετε και τα deltas. Δεν έχει διαφορά από άποψη κώδικα.
μόνο το τελικό σχήμα αλλάζει.

**Comment by michaelbzms** [comment]
Μία εκφώνηση έχει πολλά windows όμως που το καθένα έχει 13 coefficients. Εσείς ζητάτε να δείξουμε την συσχέτιση (correlation map) για ένα window και έτσι να βγάλουμε συμπεράσματα για όλη την εκφώνηση του ψηφίου από τον ομιλητή? Ή πρεπει να κάνουμε κάτι οπως να πάρουμε το μέσο correlation από όλα τα windows και να βγάλουμε συμπεράσματα από αυτό; (στο ερώτημα 4 αναφέρομαι)
