### ISSUE TITLE
Lab Αναφορές Εργαστηριακών Ασκήσεων

### ISSUE THREAD

**Issue by spyrospav** [slp-ntua/patrec-labs#6]
Καλησπέρα,

Για την παράδοση των εργαστηριακών ασκήσεων χρειάζεται να κάνουμε την αναφορά σε ξεχωριστό pdf ή μπορούμε να απαντάμε τα ερωτήματα σε jupyter notebook μαζί με τον κώδικα και στη συνέχεια να κάνουμε export το notebook ως pdf?

**Comment by efthymisgeo** [comment]
3 πράγματα ζητάμε
- ο,τι κώδικα γράφετε σε `.py`
- μια ανφορά σε ξεχωριστό .pdf
- το αρχείο `lib.py` συμπληρωμένο

**Comment by georgepar** [comment]
Προτιμάμε ξεχωριστό pdf. Δε χρειάζεται να παραδώσετε αναφορά με την
προπαρασκευή. Μόνο με την εργαστηριακή.

**Comment by LoniasGR** [comment]
Για την προπαρασκευή δεν παραδίδουμε ούτε τον κώδικα;

**Comment by georgepar** [comment]
Τον κώδικα τον παραδίδετε κανονικά για την προπαρασκευή. Θα τον συμπεριλάβετε και στην παράδοση του εργαστηρίου.

**Comment by TsiarasKon** [comment]
Οι οδηγίες παράδοσης που έχετε στην εκφώνηση αφορούν "προπαρασκευή + εργαστήριο".
Για την προπαρασκευή μόνο που λέτε κι εδώ, πού θέλετε να σας παραδώσουμε; Αν μέσω mycourses τότε:
1. Αρκεί να την παραδώσει ένας από την κάθε ομάδα 2 ατόμων;
2. Πατώντας "Υποβολή Εργασίας" εμφανίζεται ένα παράθυρο με προειδοποίηση "Η υποβολή είναι οριστική. Δε θα έχετε τη δυνατότητα αλλαγής ή διαγραφής της εργασίας σας". Να υποβάλλουμε τώρα εκεί την προπαρασκευή και να υποθέσουμε πως θα ανοίξει ξεχωριστή υποβολή εκ των υστέρων για΄το τελικό παραδοτέο "προπαρασκευή + εργαστήριο"?
Ενδεχομένως να είναι συνηθισμένες οι απορίες αυτές, απλά μερικοί πρώτοι φορά βλέπουμε mycourses.

**Comment by georgepar** [comment]
> Αρκεί να την παραδώσει ένας από την κάθε ομάδα 2 ατόμων;
Ναι. Αρκεί να έχει βάλει τα ονόματα και των 2 συνεργατών. Για διευκόλυνση μπορείτε να δώσετε και ένα όνομα στο αρχείο `patreco_AM1_AM2.zip`, όπου ΑΜ1, ΑΜ2 οι αριθμοί μητρώου των 2 συνεργατών.

> Πατώντας "Υποβολή Εργασίας" εμφανίζεται ένα παράθυρο με προειδοποίηση "Η υποβολή είναι οριστική. Δε θα έχετε τη δυνατότητα αλλαγής ή διαγραφής της εργασίας σας". Να υποβάλλουμε τώρα εκεί την προπαρασκευή και να υποθέσουμε πως θα ανοίξει ξεχωριστή υποβολή εκ των υστέρων για΄το τελικό παραδοτέο "προπαρασκευή + εργαστήριο"?

Για το τελικό θα ανοίξει ξεχωριστή υποβολή. Μην ανησυχείτε για αυτό. Αυτό το "Η υποβολή είναι οριστική" σημαίνει ότι για την παρούσα εργασία δεν υπάρχει δυνατότητα να κάνεις κάποιο amend.

**Comment by TsiarasKon** [comment]
Εμείς του μεταπτυχιακού, αν και μόλις πήραμε NTUA emails, δεν μας έχει ακόμα δοθεί ούτε φαίνεται κάπου ο ΑΜ μας. Υποθέτω σας αρκεί για την ώρα να βάλουμε απλά ονοματεπώνυμα και mails;

**Comment by georgepar** [comment]
Βαλτε το username από το mail σας

**Comment by Aria-Minaidi** [comment]
Καλησπέρα σας, εγώ είμαι από το μεταπτυχιακό, έχω τελειώσει πρόσφατα σημμυ, αλλά επειδή η σχολή βγάζει τα πιστοποιητικά διπλώματος τον Νοέμβρη, θα πάρω τότε κωδικούς και email για το μεταπτυχιακό, οπότε υποθέτω να βάλω μόνο το όνομά μου στην αναφορά και να κάνουμε υποβολή από το λογαριασμό του συνεργάτη μου;

**Comment by georgepar** [comment]
ναι. Βαλτε γενικα ότι identifier έχετε μέχρι να λυθεί το θέμα με τα ιδρυματικά accounts.

**Comment by manpad13** [comment]
καλησπερα θελω να κανω να μια διαδικαστικη ερωτηση. Την εργασια και γενικα ολες τις εργασιες τις ανεβαζουμε στο mycourses η στο courses.pclab.ece.ntua.gr γιατι μας εχει ζητηθει να κανουμε και εκει enroll και εκρεμη και σε αυτο μια εργασια

**Comment by georgepar** [comment]
Καλημέρα,

Όπως είπαμε στις ανακοινώσεις, το μάθημα θα μετακινηθεί πλήρως στο
courses.pclab.ece.ntua.gr, οπότε από εδώ και στο εξής όλες οι υποβολές θα
γίνονται εκεί
