### ISSUE TITLE
[Lab 2] Σφάλμα κατα την εκέλεση της συνάρτησης GeneralMixtureModel.from_samples()

### ISSUE THREAD

**Issue by inikokali** [slp-ntua/patrec-labs#60]
Καλησπέρα σας.

Εδώ και αρκετές ημέρες μετά από επανειλημμένες προσπάθειες μας προκύπτει το σφάλμα που αναγράφεται στο #43 . Το σφάλμα προκύπτει είτε το τρέχουμε μέσω Jupyter Notebook είτε με python script (και στους δύο διαθέσιμους υπολογιστές της ομάδας). Έχουμε δοκιμάσει να φτιάξουμε και καινούργια environments στα οποία εγκαταστήσαμε τα version των packages που έχετε δώσει. Επιπλέον διαπιστώσαμε οτι ο κώδικας ως python script δουλεύει σε άλλο υπολογιστή (ατόμου εκτός σχολής και μαθήματος) ωστόσο δεν μπορούμε να έχουμε συνεχώς πρόσβαση στον υπολογιστή αυτό. Τι μπορούμε να κάνουμε για να λύσουμε το πρόβλημα και να συνεχίσουμε την εκτέλεση της εργασίας;;

**Comment by georgepar** [comment]
υποθέτω είστε ίδια ομάδα με αυτό το comment? https://github.com/slp-ntua/patrec-labs/issues/57

**Comment by vassilispan** [comment]
Οχι δεν ειμαστε ιδια ομαδα

**Comment by georgepar** [comment]
Αναλυτική απάντηση εδώ καθώς είναι duplicate:
https://github.com/slp-ntua/patrec-labs/issues/57#issuecomment-749010527
