### ISSUE TITLE
Scaling

### ISSUE THREAD

**Issue by ChristosSgouropoulos** [slp-ntua/patrec-labs#68]
Καλησπέρα σας και καλή χρονιά . Τρέχω στο πρώτο μέρος της άσκησης το Lstm και βγάζει σκορ περίπου 35%. Και training και validation. Καταλαβαίνω ότι αυτό προκύπτει μάλλον επειδή δεν έχει γίνει scaling στους πίνακες των δεδομένων. Με τον τρόπο που ορίζετε την κλάση των δεδομένων, και ειδικότερα το split , τα δεδομένα χωρίζονται σε train και validation με βάση τα indices , και στη συνέχεια μπαίνουν απευθείας σε data loaders. Με αυτον τον τρόπο δεν μπορώ να κάνω scale μετά το split.

Επίσης επιχειρώντας να κάνω scale στο ίδιο cell που ορίζεται η κλάση , η μνήμη του kaggle γεμίζει και γίνεται restart to session. Μπορούμε να κανουμε split τα data με κάποιον άλλο τρόπο για να μπορέσουμε να φιτάρουμε scalers μετά τα splits??
Σας ευχαριστώ!

**Comment by filby89** [comment]
Καλησπέρα, 
γενικά το σκορ που περιμένετε από το LSTM είναι αυτής της τάξης. Μπορείτε να δοκιμάσετε και scaling (πιθανώς θα προσδώσει κάποιο boost) αν θέλετε. Ένας τρόπος να γίνει είναι τροποποιώντας το splitting έτσι ώστε οι DataLoaders να παίρνουν τα split datasets κατευθείαν και να μην χρησιμοποιούν SubsetRandomSampler. Με αυτό τον τρόπο υπολογίζοντας πρώτα τα επιμέρους dataset μπορειτε να κάνετε το scaling.
