### ISSUE TITLE
Βήματα 7β, 7δ

### ISSUE THREAD

**Issue by dimitriskranias** [slp-ntua/patrec-labs#77]
Το 2D CNN θέλετε να το κατασκευάσουμε και να το εκπαιδεύσουμε για τα mel-spectrograms ή τα beat-synced mel-spectrograms; (Ή σε όποιο από τα 2 βγάζουμε καλύτερα αποτελέσματα;) Γιατί από την εκφώνηση δεν είναι ξεκάθαρο (Ναι μεν λέτε να το συγκρίνουμε με το μοντέλο του 5α που υπονοεί ότι θέλουμε τα mel-spectrograms, αλλά ρωτάω για επιβεβαίωση).

**Comment by georgepar** [comment]
Επιλέξτε το καλύτερο συνδυασμό.
