### ISSUE TITLE
Lab3_Step8_CNN_Train_Validation_Loss_Values

### ISSUE THREAD

**Issue by GiorgosStakias** [slp-ntua/patrec-labs#82]
Καλησπέρα. Στο 8ο βήμα της εργαστηριακής άσκησης οι τιμές των Train_Loss και Validation_Loss για τα μονέλα μας αλλάζουν δραματικά μεταξύ διαφορετικών εκτελέσεων της προσομοίωσης. Σε άλλες εκτελέσεις ξεκινάνε απο σχετικά υψηλές τιμές (της τάξης του 0.37) και πέφτουν μέχρι και την 20η και τελευταία εποχή εκπαίδευσης σε τιμές χαμηλότερες (της τάξης του 0.15) και σε άλλες εκτελέσεις ξεκινάνε από χαμηλές τιμές (της τάξης του 0.1) και μέσα στις δύο πρώτες εποχές εκπαίδευσης σταθεροποιούνται σε πολύ χαμηλές τιμές (της τάξης του 0.05). Μπορεί κάτι τέτοιο να οφείλεται στην τυχαίότητα δημιουργίας των dataset και στις διαφορές τους από εκτέλεση σε εκτέλεση; Πώς μπορούμε να ερμηνεύσουμε πολύ χαμηλές τιμές loss από την πρώτη κιόλας εποχή εκπαίδευσης του μοντέλου; Υπάρχει περίπτωση να οφείλεται στην διαφορετική μετρική για το loss_function που χρησιμοποιούμε επειδή είναι regression τα μονέλα που εκπαιδεύουμε;

**Comment by georgepar** [comment]
Αυτό ακούγεται σαν bug αν αναφέρεσαι σε διαφορετικά runs του ίδιου μοντέλου (με τα ίδια features και τις ίδιες παραμέτρους). Το loss function δεν έχει σχέση με αυτή τη συμπεριφορά.
