### ISSUE TITLE
Spearman metric

### ISSUE THREAD

**Issue by michaelbzms** [slp-ntua/patrec-labs#85]
Για τον υπολογισμό του spearman metric υπολογίζουμε το spearman correlation για κάθε batch και στο τέλος παίρνουμε το average (αυτό εννοείτε στο 8ε;) ή ενώνουμε όλα τα predictions και ground truths και το υπολογίζουμε στο τέλος του epoch μία φορά; Είναι ισοδύναμο (γιατί δεν μου φαίνεται ισοδύναμο);

Τι εννοείτε στο 8ε με "το μέσο Spearman για όλους τους άξονες";

**Comment by georgepar** [comment]
> Για τον υπολογισμό του spearman metric υπολογίζουμε το spearman correlation για κάθε batch και στο τέλος παίρνουμε το average (αυτό εννοείτε στο 8ε;) ή ενώνουμε όλα τα predictions και ground truths και το υπολογίζουμε στο τέλος του epoch μία φορά; 

το δεύτερο

> Είναι ισοδύναμο (γιατί δεν μου φαίνεται ισοδύναμο);

Δεν είναι, αλλά πολλές φορές στην πράξη αυτό γίνεται καταχρηστικά.

> Τι εννοείτε στο 8ε με "το μέσο Spearman για όλους τους άξονες";

Άξονες εννοούμε το valence, arousal, danceability. Έχετε 3 μοντέλα (ή ένα multitask) που τα χρησιμοποιείτε για να υπολογίσετε το correlation με την μέθοδο που είπαμε παραπάνω σε κάθε άξονα και στο τέλος παίρνετε το μέσο όρο από τα 3 spearman correlations.
