### ISSUE TITLE
10 (Διαγωνισμός Kaggle)

### ISSUE THREAD

**Issue by SyllasGiorgos** [slp-ntua/patrec-labs#86]
Θα ήθελα να ρωτήσω, υπάρχει δυνατότητα υποβολής στο διαγωνισμό, μετά τις 12, μιας και είναι ανεξάρτητη από την υποβολή της υπόλοιπης άσκησης?

**Comment by LoniasGR** [comment]
Επίσης είναι κρίμα που έχουμε δύο υποβολλές μόνο. Δεν το ήξερα και δεν μπορώ να δοκιμάσω το τελικό μοντέλο μας.
