### ISSUE TITLE
Step 18

### ISSUE THREAD

**Issue by spyrgkou** [slp-ntua/patrec-labs#93]
Για το βήμα 18, οι συναρτήσεις που υπάρχουν στο lib.py, δε θα έπρεπε να έχουν και ως όρισμα ταξινομητές,
estimators για το Voting Classifiers και clf για τον Bagging, σύμφωνα με το documentation του scikit-learn ?
Γενικότερα μπορούμε να διαφοροποιήσουμε τις συναρτήσεις που ορίζονται σε αυτό το αρχείο ή να προσθέσουμε δικές μας (ή ακόμη και αυτές που μας προτείνατε να χρησιμοποιήσουμε από τον κώδικα του εργαστηρίου για το plotting του ταξινομητή, learning curve, κλπ)? 
Υποθέτω πως για την παράδοση μπορούμε να έχουμε όλες τις συναρτήσεις που έχουμε υλοποιήσει στο lib.py και ένα jupyter notebook για την απάντηση των ερωτημάτων (+report)?

**Comment by iliaskoum** [comment]
Για το βημα 18 ,για να δουμε ποιος ταξινομητης  τεινει να ταξινομει ενα ψηφιο λαθος ,πρεπει να κανουμε εναν confusion matrix για να το δειξουμε?

**Comment by georgepar** [comment]
Ναι

**Comment by Chrz95** [comment]
Αν βάλουμε τους ταξινομητές να κάνουν προβλέψεις και μετά υπολογίσουμε σε τι ποσοστό είναι ίδιες, το ίδιο δεν κάνει ;

**Comment by georgepar** [comment]
Ο πιο εύκολος τρόπος ειναι με confusion matrix. Αν θέλετε κάπως αλλιώς δεν έχουμε προβλημα, αρκεί να το δικαιολογήσετε επαρκως
