### ISSUE TITLE
Βήμα 19 

### ISSUE THREAD

**Issue by GeorgiosPapadakis** [slp-ntua/patrec-labs#95]
Καλησπέρα σας. Κατά την εκπαίδευση του νευρωτικού, μου προέκυψε ένα σφάλμα της εξής μορφής:
ValueError: operands could not be broadcast together with shapes (256,) (2,)

Έψαξα γενικά τι μπορεί να σημαίνει αλλά δεν έβγαλα άκρη.
Τι ακριβώς μας λέει ένα τέτοιο error?

**Comment by mpektkd** [comment]
Καλησπερα, μια ερωτηση για το (α) ερωτημα. Θελετε απο εμας να υλοποιησουμε την κλαση που θα κληρονομει απο την κλαση Dataset και να χρησιμοποιησουμε την Dataloader του pytorch ή θελετε και custom υλοποιηση μιας κλαησης CustomDataloader?

**Comment by georgepar** [comment]
Το πρωτο. Ένα dataset σε συνδυασμό με το dataloader

**Comment by mpektkd** [comment]
Ωραια, ευχαριστω πολυ.
