### ISSUE TITLE
Step 13γ

### ISSUE THREAD

**Issue by ManolisTr** [slp-ntua/patrec-labs#96]
Στο ερώτημα 13γ παίρνω το παρακατω σχήμα. Τι μπορεί να φταιει;
![c](https://user-images.githubusercontent.com/60068214/139538618-f40ae7b2-3f13-4dd7-8d06-88687045ff82.png)

**Comment by efthymisgeo** [comment]
Μήπως δεν εκπαιδεύεις καν τον ταξινομητη;

**Comment by ManolisTr** [comment]
Σαν όρισμα στην συνάρτηση learning_curve βάζουμε ένα μοντέλο που θέλουμε να χρησιμοποιήσει ή ένα μοντέλο που το έχουμε εκπαιδευσει σε προηγούμενα βήματα,δηλαδή:

train_sizes, train_scores, test_scores = learning_curve(
    clf5, x_train, y_train, cv=5, n_jobs=-1, 
    train_sizes=np.linspace(.1, 1.0, 5))

όπου
clf5=EuclideanDistanceClassifier()
clf5.fit(x_train,y_train)


ή 

EuclideanDistanceClassifier()
