### ISSUE TITLE
Βήμα 15γ

### ISSUE THREAD

**Issue by lole32** [slp-ntua/patrec-labs#97]
Στο βήμα 15γ) ζητάτε να συγκρίνουμε την υλοποίηση του NaiveBayes με αυτή του GaussianNB. Εννοείτε να συγκρίνουμε τα scores του καθενός, ή ολόκληρη την δικιά μας υλοποίηση της κλάσης με αυτή του Scikit learn ;

**Comment by georgepar** [comment]
Εννοούμε τα scores και βασικές διαφορές υλοποίησης
