### ISSUE TITLE
Βήμα 15α

### ISSUE THREAD

**Issue by Desoforos** [slp-ntua/patrec-labs#98]
Καλησπέρα σας. Δεν θέλω να κάνω σποιλ απλά έχω κολλήσει πολύ σε αυτό.
Στο βήμα 15α στην μέθοδο predict της κλάσης που μας δίνετε θέλετε ουσιαστικά για τον υπολογισμό του P(xi|y) (όπου xi κάποιο πίξελ(τιμή) μιας εικόνας του X_test, y κάποιο label (0-9) ) να χρησιμοποιήσουμε το scipy.stats.norm(mean,std).pdf(xi), όπου mean,std είναι η μέση τιμή και διασπορά του συγκεκριμένου πίξελ(εννοώ θέση) για το συγκεκριμένο label;  (και αυτό να το επαναλάβουμε για όλα τα πίξελς για κάθε label από την αρχή και κρατάμε το μεγαλύτερο γινόμενο άρα και label)
Αν ναι, πρώτον μου βγάζει πρόβλημα γιατί σε πολλά ψηφία και σε πολλά πίξελς τους η διασπορά μου βγαίνει μηδέν (ίσως επειδή όλα τα δείγματα του x_train με το ίδιο label είχαν την ίδια τιμή-μάλλον 0- στο συγκεκριμένο πίξελ?)
Δεύτερον, ακόμα και αν δοκιμάσω την διασπορά να είναι 1, για μικρό X_test δουλεύει κάπως ικανοποιητικά αλλά για όλο το X_test παίρνει πάρα πολλή ώρα. Φαντάζομαι δεδομένων των παραπάνω loops και πράξεων είναι λογικό(;) .

**Comment by georgepar** [comment]
> να χρησιμοποιήσουμε το scipy.stats.norm(mean,std).pdf(xi);

Νομίζω είναι πιο απλό να γράψετε με το χέρι την κανονική κατανομή, αλλά μπορείτε και με την υλοποίηση του scipy

> (και αυτό να το επαναλάβουμε για όλα τα πίξελς για κάθε label από την αρχή και κρατάμε το μεγαλύτερο γινόμενο άρα και label)

Εδώ δεν καταλαβαίνω ακριβώς την ερώτηση αλλά είναι πολύ κοντά στο spoil.

> βγάζει πρόβλημα γιατί σε πολλά ψηφία και σε πολλά πίξελς τους η διασπορά μου βγαίνει μηδέν

Αν η διασπορά βγαίνει 0, ένα κλασσικό τρικ είναι να προσθέσεις μια μικρή σταθερά (1e-5) για να αποφύγεις τις διαιρέσεις με το 0.

> για μικρό X_test δουλεύει κάπως ικανοποιητικά αλλά για όλο το X_test παίρνει πάρα πολλή ώρα. Φαντάζομαι δεδομένων των παραπάνω loops και πράξεων είναι λογικό(;) 

Αν η υλοποίηση που έχετε κάνει είναι αργή, είναι πιθανότατα επειδή έχετε loops. Αν δοκιμάσετε μια vectorized υλοποίηση θα είναι σίγουρα πιο γρήγορη.
