### ISSUE TITLE
[Βήμα 18] Top Mispredictions per Classifer

### ISSUE THREAD

**Issue by chrisdim** [slp-ntua/patrec-labs#99]
Καλησπέρα,
Στο βήμα 18, προκειμένου να δω ποιοι classifiers θα συνδυαστούν με τεχνικές ensembling, ως πρώτο στάδιο τυπώνω το ποια ψηφία κάνουν περισσότερο συχνά ως misclassified δεδομένου ενός dataset. Όταν αυτό το set είναι το X_test τότε υπάρχουν διαφοροποιήσεις μεταξύ των classifiers (πχ ο ένας κάνει πιο συχνά λάθος το ψηφίο 5, ενώ ο άλλος το 4), ενώ όταν το set αυτό είναι το X_train τότε σχεδόν όλοι οι classifiers κάνουν mispredictions με ακριβώς την ίδια σειρά ψηφίων (άρα δεν έχει νόημα να εξάγω συμπεράσματα για τον πιθανό συνδυασμό ταξινομητών ?? ). Έχει νόημα η εξαγωγή των mispredictions να γίνεται στο X_test αντί του Χ_train;
Ευχαριστώ.

**Comment by georgepar** [comment]
>  Έχει νόημα η εξαγωγή των mispredictions να γίνεται στο X_test αντί του Χ_train;

Για αυτό το λόγο χωρίζουμε ένα validation set ή βάζουμε αυτή τη διαδικασία μέσα στο cross validation.

Η διαδικασία που κάνεις αυτή τη στιγμή είναι μέρος του model selection, οπότε το test είναι σαν να μην υπάρχει.
